[package]
name = "oh-my-vllm-zmq-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "oh-my-vllm-zmq-worker"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum = "0.8"
libc = "0.2"
clap.workspace = true
oh-my-vllm-kv-cache.workspace = true
oh-my-vllm-scheduler.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_json = "1"
thiserror.workspace = true
tokio.workspace = true
tokio-stream = "0.1"
tracing.workspace = true
tracing-subscriber.workspace = true
zeromq.workspace = true

[build-dependencies]
sha2.workspace = true
