"""oh_my_vllm.worker.spec_decode — MTP speculative decoding helpers.

For Qwen3.5, vLLM implements MTP via Step3p5MTPProposer, which is activated
by setting a SpeculativeConfig on VllmConfig with model_type "qwen3_5_mtp".
vLLM's existing rejection sampler then writes accepted+bonus tokens into
ModelRunnerOutput.sampled_token_ids, with each request's list extended to
include accepted draft tokens followed by the bonus token.

This module provides:
  - build_speculative_config: construct the SpeculativeConfig for Qwen3.5 MTP.
  - parse_mtp_output: extract (next_token_id, num_accepted_drafts, new_drafts)
    per request from the extended sampled_token_ids lists.
"""

from __future__ import annotations


def build_speculative_config(
    model_path: str,
    num_speculative_tokens: int,
) -> object:
    """Return a SpeculativeConfig for Qwen3.5 MTP.

    Passes the same model_path as the speculative model — vLLM detects
    mtp_num_hidden_layers from the HF config and routes to Step3p5MTPProposer
    automatically when model_type resolves to qwen3_5_mtp / step3p5_mtp.

    Args:
        model_path: Path to the Qwen3.5 weights directory.
        num_speculative_tokens: Draft tokens to propose per decode step (e.g. 4).

    Returns:
        vllm.config.speculative.SpeculativeConfig instance.
    """
    from vllm.config.speculative import SpeculativeConfig

    return SpeculativeConfig(
        model=model_path,
        num_speculative_tokens=num_speculative_tokens,
        # draft_sample_method="greedy" is default and matches vLLM main baseline.
    )


def parse_mtp_output(
    sampled_token_ids: list[list[int]],
    num_speculative_tokens: int,
) -> list[tuple[int, int, list[int]]]:
    """Parse the rejection-sampler output into per-request tuples.

    When spec decode is active, each entry in sampled_token_ids has length
    between 1 (all drafts rejected) and num_speculative_tokens + 1 (all
    accepted plus bonus).  The layout is:
        [accepted_draft_0, ..., accepted_draft_k, bonus_token]

    We treat the final element as the "next token" for the request's output
    stream.  Accepted drafts are the elements before it.

    When spec decode is inactive (list length == 1), num_accepted is 0 and
    new_draft_token_ids is empty — same semantics as the non-MTP path.

    Args:
        sampled_token_ids: Per-request list from ModelRunnerOutput.
        num_speculative_tokens: How many drafts were proposed (used only for
            validation; the actual accepted count comes from list length).

    Returns:
        List of (next_token_id, num_accepted_draft_tokens, new_draft_token_ids).
        new_draft_token_ids is always empty here — the next step's drafts are
        generated by the MTP proposer inside vLLM's model runner, not by us.
    """
    results = []
    for token_list in sampled_token_ids:
        if not token_list:
            results.append((0, 0, []))
            continue
        # The bonus token is always the last element; accepted drafts precede it.
        next_token = token_list[-1]
        num_accepted = max(0, len(token_list) - 1)
        # Cap at num_speculative_tokens in case vLLM ever returns extra entries.
        num_accepted = min(num_accepted, num_speculative_tokens)
        results.append((int(next_token), num_accepted, []))
    return results
