export const chapters = {
  Basics: { number: 1, title: "输入与生成: 从 HTTP 请求到 token 历史", needs: [], question: "文字怎样成为模型输入, 一次生成如何推进?" },
  Ownership: { number: 2, title: "进程分工: Rust 引擎与 Python worker", needs: ["Basics"], question: "两个进程如何启动, 各自拥有哪些状态?" },
  Requests: { number: 3, title: "请求管理: 状态变化与连续批处理", needs: ["Ownership"], question: "多条请求怎样排队, 提交和完成?" },
  Budget: { number: 4, title: "计算分配: token 预算与分块 prefill", needs: ["Requests"], question: "每轮处理多少输入, 为什么 32768 分成 32144 + 624?" },
  Cache: { number: 5, title: "缓存布局: 784-token 页与 FA / GDN 状态", needs: ["Budget"], question: "逻辑页怎样对应物理内存, 为什么要保存两类状态?" },
  Reuse: { number: 6, title: "缓存复用: 前缀哈希, 引用计数与抢占恢复", needs: ["Cache"], question: "怎样复用相同开头, 并在内存不足时继续推进?" },
  Protocol: { number: 7, title: "消息通信: 执行协议, 取消与错误处理", needs: ["Reuse"], question: "跨进程结果如何对应请求, 取消和错误如何收尾?" },
  Model: { number: 8, title: "模型计算: Qwen, FP8 投影与混合注意力", needs: ["Protocol"], question: "输入怎样经过 64 层计算, 成为下一 token 的分数?" },
  Sampling: { number: 9, title: "输出生成: 采样, 语法约束与流式响应", needs: ["Model"], question: "分数怎样成为合法输出, 再逐段送回客户端?" },
  Speculation: { number: 10, title: "多 token 预测: MTP 提议, 验证与状态提交", needs: ["Sampling"], question: "怎样一次验证多个草稿, 同时保留正确的历史与缓存?" },
  Compilation: { number: 11, title: "执行优化: Semantic IR, CUDA Graph 与自有内核", needs: ["Speculation"], question: "语义操作怎样选择实现, 编译并复用 GPU 执行流程?" },
  Validation: { number: 12, title: "验证方法: 正确性, 性能测量与验收证据", needs: ["Compilation"], question: "如何证明执行结果正确, 并复现一次性能验收?" },
  DSpark: { number: 13, title: "DSpark: 特征注入, 草稿分布与前缀验证", needs: ["Validation"], question: "独立草稿模型怎样读取目标特征, 提出七个候选并保持采样分布?" },
};

// Each record is checked against the current source, then shown in its chapter.
// Layout: chapter, file, source anchor, responsibility, implementation and decision.
export const coverage = [
  ["DSpark", "python/oh_my_vllm/models/dspark.py", "class DSparkModel", "DSparkCheckpoint / DSparkModel: 加载, 双源计算与学习头", "校验固定配置与 62 个 BF16 张量, 绑定稳定文件的 SHA-256. 目标层特征投影为 context KV, 七个临时 noise 行经过五层双向注意力; Markov 根据前一候选修正 logits, confidence 预测接受概率."],
  ["DSpark", "python/oh_my_vllm/worker/dspark.py", "class DSpark:", "DSpark: 已保留特征注入与因果提议", "复用目标 FA 页编号, 只注入实际保留的输入. 贪心链保留在设备上, 随机链保存真实 q; 默认累计 confidence 阈值 0.2, 从首项起向右截断, 实际提议 0 至 7 个; grammar 临时前进后回滚."],
  ["DSpark", "python/oh_my_vllm/worker/dspark_graph.py", "class DSparkContextGraph", "DSparkContextGraph / DSparkGraph: 提交与提议图", "小批量 context 图备份目的槽, 预热与捕获后恢复, replay 复制动态位置后正式写入; 单独 pool 与 32 项预算, 覆盖全部合法行数. 提议图仅读 context, 使用独立 16 项预算, 输出在同族下次捕获前消费."],
  ["DSpark", "python/oh_my_vllm/kernels/dspark_attention.py", "def attention(", "DSpark 准备, context 写入与双源 attention", "Q/K 使用完整 128 维 NeoX YaRN, 保留 Qwen3 BF16 舍入. 自有 CUDA 将持久前缀与七行 block 分开读取, split-KV 计算局部结果并稳定合并."],
  ["DSpark", "python/oh_my_vllm/ir/dspark.py", "def block_attention(", "DSpark 语义操作与参考", "为独立 RMS, Q/K/RoPE, context append 和双源 attention 注册参考, fake 元数据和 CUDA 实现. append 明确修改缓存, attention 仅读缓存."],
  ["DSpark", "python/oh_my_vllm/kernels/dspark_tilelang_reference.py", "def attention(", "新增 DSpark 操作的 TileLang 比较 provider", "实现同一双源注意力与 BF16 舍入契约, 为自有 CUDA 新增路径提供正式算子比较. 通过显式后端选择使用, 生产 CUDA 路径保持显式."],
  ["DSpark", "python/oh_my_vllm/models/qwen.py", "    def forward_features(", "Qwen.forward_features: 同位置目标特征", "按零基层号 5, 19, 33, 47, 61 重建 BF16 层输出, 按该顺序拼接成每行 25600 维, 最终归一化 hidden 另行返回."],
  ["DSpark", "python/oh_my_vllm/worker/sampler.py", "    def draw_speculative_rows(", "draw_speculative_rows: 随机提议的完整概率接受", "从实际 q 读取候选概率, 以 min(1,p/q) 接受, 拒绝后抽取正残差分布, 全部接受后抽取目标 bonus. 复用原有逐行提交与有效性契约."],
  ["DSpark", "python/oh_my_vllm/worker/model_runner.py", "    def _proposer(", "RuntimeConfig / proposer: 模式与提交整合", "普通, MTP4 和 DSpark7 分别选择 proposer; DSpark 获取目标特征, 在 sampler/history 已提交后生成下一轮候选. 完成和抢占清除对应请求状态."],
  ["DSpark", "crates/zmq-worker/src/spec_bench.rs", "pub async fn", "同进程 MTP / DSpark 配对测量", "共用目标权重和固定硬件, 请求结束后清空前缀管理再切换草稿模式. 记录完整引擎耗时, 真实验证/接受草稿数, 步数与每请求 TTFT."],
  ["DSpark", "benchmarks/speculative.py", "def compare_rounds(", "compare_rounds: 吞吐统计与配对增益", "长输入 batch 1, 2, 4 各运行三轮, 每模式两次预热和五对交替正式测量. 报告每轮 TPS 中位数, 极差和分层配对 bootstrap 增益下界, TTFT 单独报告; DSpark 暂无高于 MTP 的新增性能门槛."],
  ["DSpark", "crates/zmq-worker/src/main.rs", "    fn prompts(&self,", "BenchArgs.prompts / parse_prompts: 独立自然语料校准", "bench --prompt-file 读取目标 tokenizer 生成的逐行 ID, 在启动 worker 前核对 batch, 每行长度, context 和词表. 调优语料与固定合成 spec-bench 负载分别记录, 复用实际引擎计时与草稿计数."],
  ["Basics", "crates/zmq-worker/src/serving/request.rs", "pub fn normalize(", "normalize: 统一 Chat 与 Responses 输入", "校验字段和模型名, 合并对话历史, 转换工具与输出格式. 把不同 API 整理成同一种准备输入, 后续调度器只处理 token."],
  ["Basics", "python/oh_my_vllm/worker/serving.py", "    def prepare_inputs(", "ServingAdapter.prepare_inputs: 模板, 分词与输入预算", "按模型本地模板组织角色和工具记录, 检查提示词加输出预算, 返回 ID, SamplingParams 和 Generation. 准备阶段构造数据, 桥接主线程再安装活跃状态."],
  ["Ownership", "crates/zmq-worker/src/main.rs", "async fn run()", "run / execute_batch: CLI 的 Serve 与 Bench 路线", "配置 worker, 初始化 Rust 缓存与调度器, 分派 HTTP 或批量基准入口. Bench 使用同一调度和模型执行链, 通过合成 ID 构造负载."],
  ["Ownership", "crates/zmq-worker/src/lib.rs", "pub use", "crate 导出边界", "导出 WorkerClient 和配置, 把命令入口与通信实现分开, 供 serving 与 benchmark 共用."],
  ["Ownership", "python/oh_my_vllm/worker/model_runner.py", "class OhMyVllmWorker", "OhMyVllmWorker: 初始化, 执行与清理", "init_device / load_model / initialize_cache 建立单卡运行时; execute_model 检查计划, 组合输入, 调用 forward, 采样并提交; shutdown 释放图和模型引用."],
  ["Ownership", "python/oh_my_vllm/worker/runtime.py", "def identity(", "identity / verify_loaded_modules: 运行身份", "记录解释器, 软件版本和内核构建来源, 检查 Python 路径与已加载模块/动态库. 独立运行约束在启动与退出时都留下可核对的证据."],
  ["Ownership", "python/oh_my_vllm/worker/logging_utils.py", "def configure_logging(", "configure_logging: 关联日志", "统一日志格式并关联运行编号, 使 Rust 派发, Python 执行和请求完成的记录可以对应."],
  ["Requests", "crates/scheduler/src/request.rs", "pub struct Request", "Request: 已确认历史与生命周期", "保存提示词长度, 历史, 在途进度, 输出上限和草稿; append_token / set_drafts 分开维护已确认与候选数据."],
  ["Requests", "crates/scheduler/src/lib.rs", "    pub fn schedule(", "Scheduler: 接纳, 排队, 验证与提交", "schedule 先推进运行请求再接纳等待请求; pause / resume 处理背压; validate_output 在 update 修改历史之前检查结果契约, abort 清理请求和缓存."],
  ["Requests", "crates/scheduler/src/output.rs", "pub struct ScheduledRequest", "ScheduledRequest / SchedulerOutput / WorkerOutput", "长期请求状态, 单轮输入片段和返回结果分别建模, 让在途输入数量与输出数量有明确归属."],
  ["Budget", "crates/scheduler/src/lib.rs", "    fn aligned_prefill(", "aligned_prefill: 按预算和页边界选片段", "未完成的长 prefill 按页调整终点, 同时在最后完整页与尾段之间切开. 正输入量的返回值至少为 1, 让小预算也能前进."],
  ["Cache", "crates/kv-cache/src/group.rs", "pub struct GroupManager", "GroupManager: 分组块表与需求计算", "FullAttention 保存按位置增长的页, Mamba align 保存恢复点与候选槽. get_num_blocks_to_allocate 计算缺口, allocate_new_blocks 建表, remove_skipped_blocks 回收以后不再读取的旧状态."],
  ["Cache", "crates/kv-cache/src/coordinator.rs", "pub struct HybridCoordinator", "HybridCoordinator: 两类缓存共同分配", "统一 FA/GDN 命中长度, 先检查需求与水位, 再引用命中块并分配新块. --mamba-blocks 可提供独立 GDN 容量; 省略时共享池."],
  ["Cache", "python/oh_my_vllm/worker/batch_plan.py", "def plan_request(", "plan_request / validate_batch / PlannedRequest.commit", "在 CPU 核对历史与地址, 拒绝跨请求写入别名; 为每个输入选择状态写入点, 根据保留输出选下一源槽和边界复制."],
  ["Cache", "python/oh_my_vllm/worker/tensors.py", "def device_vectors(", "device_tensor / device_vectors / device_page_tables", "把小整数元数据合并传到 GPU, 再用视图取出位置和槽编号; 块表按实际每请求输入行数展开. non_blocking 使用同一 CUDA 流保持消费顺序."],
  ["Reuse", "crates/kv-cache/src/hash.rs", "pub fn hash_block_tokens(", "hash_block_tokens / hash_request_tokens", "将父摘要, 当前 ID 和额外键连成链, 长度编码区分不同组合. 使用 SHA-256 的前 8 字节作为 u64 键; 按完整块增量延长摘要."],
  ["Reuse", "crates/kv-cache/src/pool.rs", "pub struct BlockPool", "BlockPool: 可用队列, 前缀索引和引用计数", "touch 先把命中块移出可用队列, 再增加引用; free_blocks 在最后引用释放时归还. 无缓存价值的块优先复用, 已缓存浅前缀尽量保留."],
  ["Reuse", "crates/kv-cache/src/block.rs", "pub struct KVCacheBlock", "KVCacheBlock / FreeKVCacheBlockQueue", "块编号是 arena 数组下标, 记录保存引用和摘要, 队列使用编号索引的双向链接. 已命中的空闲块可以直接从队列摘除, 批量分配先检查数量."],
  ["Reuse", "crates/kv-cache/src/lib.rs", "pub use", "缓存 crate 公共入口", "导出 BlockPool, GroupManager, HybridCoordinator 和哈希类型, 让调度器依赖逻辑管理层而非 GPU 张量."],
  ["Protocol", "crates/zmq-worker/src/client.rs", "pub struct WorkerClient", "WorkerClient: 启动握手, RPC 对应与子进程退出", "绑定 DEALER, 启动 Python, 校验返回类型和 rpc_id; 等待 execute 时可暂存 prepared. 取消准备保留有界记录, 防止迟到回复重新接纳."],
  ["Protocol", "crates/zmq-worker/src/protocol.rs", "pub enum RustMessage", "RustMessage / PythonMessage: msgpack 消息", "区分 init, register, prepare, execute, abort, shutdown 和各类回复. 序列化只发送实际执行所需字段, cache_hit_tokens 保留为 Rust 统计."],
  ["Protocol", "crates/zmq-worker/src/error.rs", "pub enum Error", "Error: 通信和 worker 故障", "把编码, 通信, 超时, 协议和子进程退出转换成有类型的错误, 交给引擎决定是否结束运行."],
  ["Protocol", "python/oh_my_vllm/worker/zmq_bridge.py", "def serve(", "serve / _PrepareExecutor / _encode_worker_output", "DEALER 主循环解码消息, 单个 CPU 准备线程生成不可变输入, 主线程安装状态. abort 取消排队或丢弃运行中的准备结果, execute 返回带编号的结果."],
  ["Protocol", "python/oh_my_vllm/worker/protocol.py", "class ScheduledRequest", "Python 消息 dataclass", "定义调度输入和请求结果, 包括 text, finish_reason, reasoning_tokens 与请求级 error. 模型 worker 按 request_id 匹配长期状态."],
  ["Model", "python/oh_my_vllm/models/qwen.py", "class Qwen", "Checkpoint / Linear / Batch / Layer / Qwen", "直接加载 safetensors, 校验架构, 将缩放布局相同的投影合并. Linear 按有无 scale 分为 FP8 与普通 F.linear, GDN b/a 使用普通 BF16 投影, 按三层 GDN 加一层 FA 重复 16 次. 残差与归一化串联, 最后投影到词表分数; MTP 头复用 embedding 和输出权重."],
  ["Model", "python/oh_my_vllm/kernels/fp8.py", "def linear(", "quantize / linear: 分块 FP8 GEMM", "每行每 128 元素量化激活, 权重按 128x128 缩放. <=32 行选 FlashInfer TRT-LLM, 更多行选 CUTLASS; 保留 BF16 结果与融合 SiLU 的舍入步骤."],
  ["Model", "python/oh_my_vllm/kernels/attention.py", "class PagedAttention", "PagedAttention / append: prefill 路由与 KV 写入", "长查询收集活跃 KV 走 ragged TRT-LLM, 中等查询走原生分页 context, 较短查询走 FA2. 持久缓存保持 Rust 的 784-token 页布局."],
  ["Model", "python/oh_my_vllm/kernels/attention_prepare.py", "def prepare_attention(", "prepare_attention: Q/K 归一化, RoPE 与写缓存", "在完整准备链中保持位置与物理槽对应, 合并中间数据读写. 负槽编号跳过 KV 写入, 仍生成当前 Q."],
  ["Model", "python/oh_my_vllm/kernels/gdn.py", "def recurrent(", "normalize_qk / recurrent / prefill", "decode / 草稿验证执行递归更新并保存候选状态, 多于一行且无草稿的 prefill 调用 FlashInfer. 显式归一化 Q/K, 将 log-decay 转成乘法衰减, 保留状态精度约束."],
  ["Model", "python/oh_my_vllm/kernels/convolution.py", "def causal_conv(", "causal_conv: 最近三个输入与当前位置", "使用每请求读槽及每 token 写槽, 做四位置因果卷积和 SiLU. 共享源与候选写入隔离, 本请求的私人源可原地更新, 允许 packed 投影视图的 token stride."],
  ["Model", "python/oh_my_vllm/kernels/normalization.py", "def add_rms_norm(", "rms_norm / rotary / rms_rotary / add_rms_norm", "FP32 计算 RMS 与门控, 保存 BF16 舍入点. RoPE 只旋转 256 维头的前 64 维, 长位置相位用 FP64 计算再求三角函数."],
  ["Model", "python/oh_my_vllm/kernels/elementwise.py", "def delta_gates(", "silu_mul / delta_gates: 逐元素融合", "将 gate/up 的 SiLU 乘法和 GDN 衰减与更新门转换为密集输出. 融合减少中间数组读写, 接口保留数学和舍入顺序."],
  ["Sampling", "python/oh_my_vllm/worker/sampling.py", "class SamplingParams", "SamplingParams / GrammarOutput", "校验温度, top-k/top-p, 惩罚, seed 和输出上限; GrammarOutput 的每一位表示一个 ID 是否允许被选取."],
  ["Sampling", "python/oh_my_vllm/worker/sampler.py", "def probabilities(", "probabilities / greedy_rows / verify_rows / RequestSampler", "根据已确认历史调整分数, 应用逐行语法位掩码, 再筛选和采样. 惩罚计数与随机生成器按请求保留; 无惩罚贪心路径只回传选中 ID 和有效标志."],
  ["Sampling", "python/oh_my_vllm/worker/serving.py", "class Generation", "Generation.consume / ServingAdapter.masks", "只提交停止条件之前保留的 ID, DecodeStream 保留跨 token 的 UTF-8 片段, 暂存可能属于 stop 前缀的字符. 草稿语法先试探再回滚, 正式提交时再推进 matcher."],
  ["Sampling", "crates/zmq-worker/src/serving/mod.rs", "async fn run_engine(", "HTTP handlers / run_engine / StreamBuffer / Store", "准备接纳与 execute 交错, 背压暂停调度但保留缓存, 断连和超时取消请求. 流式缓冲有界; 结束后限时排空, Responses 存储限制数量与体积."],
  ["Sampling", "crates/zmq-worker/src/serving/parser.rs", "pub struct Parser", "Parser.feed / feed_length / ToolProgress", "增量识别推理, 正文和工具调用, 保留不完整标记直到下一片段. 按 schema 恢复类型, 检查标签和重复参数, 长度截断时丢弃未闭合工具调用."],
  ["Sampling", "crates/zmq-worker/src/serving/events.rs", "pub struct Output", "Output.start / delta / finish / history", "把解析后的增量翻译为 Chat 或 Responses 事件, 统计输入/缓存/输出/推理用量, 组装完成响应并保存可重放历史."],
  ["Speculation", "python/oh_my_vllm/worker/mtp.py", "class MTP", "MTP.propose / validate_state / forget / _run", "MTP 行 p 使用目标 hidden[p-1] 与 token[p]. 缓存边界隐藏特征, 验证后选已接受状态; 四草稿一路在图中产生, 接近分配边界时逐步缩短提议."],
  ["Speculation", "python/oh_my_vllm/kernels/mtp_attention.py", "class MTPAttention", "MTPAttention: 从位置 1 开始的注意力", "MTP 没有位置 0, 因此长查询只收集有效 KV, decode 使用带 first=1 的项目注意力核. 因果长度逐查询保留."],
  ["Speculation", "python/oh_my_vllm/kernels/decode_attention.py", "def decode(", "decode: 普通与分组草稿验证注意力", "普通每请求一个查询, MTP 最多五个, DSpark 最多八个, 每查询保留因果终点. split-KV 先算局部最大值与加权和, 再稳定合并; 允许非对齐 cache 视图并保留克隆统计."],
  ["Compilation", "python/oh_my_vllm/ir/__init__.py", "from .", "IR 公共入口", "导出 compile_forward, 优先级和选择证据. 模型与内核入口导入各语义模块时注册对应操作, 使第一次调用前完成生产 provider 注册."],
  ["Compilation", "python/oh_my_vllm/ir/core.py", "class Operation", "Operation / TensorSpec / compile_forward / lower_to_inductor", "按形状, stride, dtype 和路由选择实现, 首次选择后冻结优先级. 全图编译将语义节点换成 schema 匹配的 provider, 校验 fake 输出, 再交给 Inductor."],
  ["Compilation", "python/oh_my_vllm/ir/fp8.py", "def linear(", "FP8 语义操作", "定义量化与矩阵投影的 PyTorch 参考, fake 输出形状及 CUDA provider. fused silu_gate 是独立明确的数学路径."],
  ["Compilation", "python/oh_my_vllm/ir/pointwise.py", "def add_rms_norm(", "逐元素与归一化语义", "注册 SiLU 乘法, GDN gates, RMS 和残差融合, 定义连续输出布局. late rewrite 只融合相邻且单次使用的 SiLU 到 FP8 投影."],
  ["Compilation", "python/oh_my_vllm/ir/recurrent.py", "def gdn_recurrent(", "递归与卷积语义", "把 pool 声明为会被修改的参数, 提供 FP64 参考步骤和 fake 输出. provider 的修改声明必须与语义 schema 完全对应."],
  ["Compilation", "python/oh_my_vllm/ir/state.py", "def prepare_attention(", "注意力准备与持久 KV 修改", "将完整 Q/K/RoPE/V/写页链声明为一个语义操作, 明确 cache 修改, 保留 packed stride 与 Q 输出布局."],
  ["Compilation", "python/oh_my_vllm/ir/attention.py", "def planned_attention(", "planned_attention: 主机计划与显式动态数据", "CPU handle 标识已规划 wrapper, 动态表和长度仍作为输入. 根据固定 route 选择分页, 原生 decode 或项目 attention 实现."],
  ["Compilation", "python/oh_my_vllm/ir/gdn_prefill.py", "def gdn_prefill(", "GDN 长序列语义", "返回输出和最终状态, 后续有序 index_copy_ 写回持久 pool. FlashInfer provider 和参考实现使用同一初始状态与序列偏移契约."],
  ["Compilation", "python/oh_my_vllm/ir/logits.py", "def logits_gemm(", "词表投影语义", "声明 hidden 与 head 的矩阵乘法, 小行数用独立 CuTe-DSL GEMM, 输出 FP32 分数供采样."],
  ["Compilation", "python/oh_my_vllm/worker/decode_graph.py", "class DecodeGraph", "DecodeAttention / DecodeGraph / DraftGraph / ProposalGraph", "固定形状与内存地址, replay 复制当前 ID, 位置, 表和读写槽. 捕获前备份会修改的缓存, 最后恢复; 三图族各用独立内存池."],
  ["Compilation", "python/oh_my_vllm/worker/graph_cache.py", "class GraphCache", "GraphCache: 有界捕获与替换", "图缓存满时要求新形状多次出现且更热, 保留族下限和 4 GiB 捕获余量. 替换成功后才释放旧图, MTP 重捕获触发共享冷却."],
  ["Compilation", "python/oh_my_vllm/kernels/backend.py", "def kernel(", "kernel: 进程级 CUDA / TileLang 选择", "默认 CUDA; 显式 tilelang 用冻结比较实现. 缺少 CUDA 入口直接报错, 运行过程中保持同一后端选择."],
  ["Compilation", "python/oh_my_vllm/kernels/cuda_backend/__init__.py", "def compiled():", "compiled / factory_for / provenance", "以源码, 编译器和 torch 版本生成缓存摘要, TVM FFI 编译并导出 CUDA 入口. 所有调用使用调用者的 CUDA 流, 记录加载来源和变体计数."],
  ["Compilation", "python/oh_my_vllm/kernels/cuda_backend/kernels.cu", "TVM_FFI", "原生 CUDA 算子与主机入口", "实现量化, 归一化, RoPE/写 KV, 卷积, GDN 和 split-KV 注意力; 采用 warp 归约, 向量读写和形状分派, 并在主机入口检查布局与地址范围."],
  ["Validation", "python/oh_my_vllm/ir/coverage.py", "def check_coverage(", "check_coverage: 模型语义调用清单", "核对模型调用点与已注册操作, 审计低层直接导入例外, 防止某个新模型路径绕过语义层."],
  ["Validation", "benchmarks/ttft.py", "def summarize(", "EngineCore 首次输出与吞吐测量", "启动 Rust Bench 入口, 保留每次请求计时, 以每轮最慢 TTFT 和输出吞吐汇总中位数及离散程度, 检查负载和比较门槛."],
  ["Validation", "benchmarks/measurement.py", "def audit(", "运行身份与测量阶段审计", "记录硬件和缓存身份, 查找 measured 阶段的编译/捕获日志, 审计编译缓存的文件变化, 核实预热完成后的稳定执行."],
  ["Validation", "development/kernels/cases.py", "def cases(", "算子最大形状用例", "静态推导生产路径边界, 将 shape 与布局纳入正式算子验收, 与冻结 TileLang 比较; 微调脚本和原始 profiling 留在仓库外."],
];
