export const readingSyntax = {
  rust: "Rust 中 pub 表示可访问, struct 定义记录, fn 定义函数, -> 标注返回类型. usize 用于数量和下标, u32 / u64 是非负整数类型. Vec<T> 是列表, Option<T> 表示有值 (Some) 或无值 (None). 冒号后是类型. self 表示当前对象, & 表示借用引用, let 定义变量, mut 表示可修改. if / else 选择分支, return 返回结果. len() 取列表长度; a..b 表示从 a 到 b 之前的区间. #[derive(Debug)] 为记录自动提供调试打印能力.",
  python: "Python 中 def 定义函数, self 表示当前对象, 参数名后的冒号可标注类型, -> 标注返回类型. 行末冒号引出缩进的代码块. list[int] 是整数列表, int | None 表示整数或空值. len() 取长度, for 遍历列表, if 判断条件, raise ValueError 拒绝非法输入. 缩进表示语句属于哪个分支.",
};

export const sourceNotes = {
  tokenHistory: {
    title: "token_ids: 请求的 token 历史",
    intro: "这是 Request 记录中的一个字段. 这里的列表保存提示词和已经确认的输出, 每个整数对应词表中的一个片段.",
    entries: [["token_ids", "按顺序保存的 token ID 列表, 类型是 Vec<u32>.", "模型读取这些 ID. 生成被确认后, 新 ID 加到列表末尾, 供后续计算使用."]],
  },
  computedCounters: {
    title: "两个计算进度字段",
    intro: "缓存保存模型已经算出的中间结果, 供下一轮复用. 注释中的 KV 是 key/value, 即模型用来读取历史的两组数值. GDN 将历史信息逐步汇入一个状态, 源码沿用 Mamba 名称. 本项目将历史按每块 784 个 token 管理, align-mode 表示在选定块边界保存可恢复的 GDN 状态. 计数表示这两类缓存共同可用的进度.",
    entries: [
      ["num_computed_tokens", "已提交且缓存可用的 token 数, 也是下一轮输入的起点.", "已提交 2 个 token 时, 下一轮从历史下标 2 开始. worker 的结果确认后才推进这个计数."],
      ["num_in_flight_tokens", "本轮已经派发, 尚未提交的输入 token 数.", "派发 1 个输入时为 1. Rust 检查返回结果后, 将它计入已提交进度并清零此字段."],
    ],
  },
  request: {
    title: "Request 的 9 个字段",
    intro: "Request 是 Rust 为一条请求保存的状态记录. RequestId 是 u64 请求编号, BlockHash 是用 u64 保存的前缀摘要. 块是固定长度的历史片段, 本项目每块 784 个 token; 前缀摘要用于查找这些片段的缓存. MTP (Multi-Token Prediction) 先提出多个候选 token, 再由目标模型验证; 尚待验证的候选叫作草稿.",
    entries: [
      ["id", "这条请求的唯一编号, 类型是 RequestId.", "把调度计划, 缓存分配, worker 返回结果和取消操作对应到同一条请求."],
      ["prompt_len", "最初提示词的 token 数, 请求创建时确定.", "即使历史继续增长也保留原值. token_ids.len() 减去它, 得到已生成的 token 数."],
      ["token_ids", "完整的已确认历史: 提示词加上已确认的输出 ID.", "用于选择本轮输入和保存生成结果. 示例 [17, 92, 6] 加入输出 42 后成为 [17, 92, 6, 42]."],
      ["draft_token_ids", "MTP 提出的待验证 token ID 列表.", "调度时将草稿计入输入预算. worker 返回后清空旧草稿, 再安装下一轮草稿. 普通生成时为空."],
      ["num_computed_tokens", "已经提交, 且模型缓存可用的历史前缀长度.", "决定下一轮从哪个位置开始计算. 新请求通常为 0, 命中可复用前缀时可从命中位置开始."],
      ["num_in_flight_tokens", "最近一轮已发给 worker, 尚未提交的输入数量.", "校验返回结果并计算本轮结束位置. 派发后增加, 确认后清零, 防止把在途计算提前当成可用缓存."],
      ["max_tokens", "允许生成的输出 token 数上限.", "限制输出历史的增长并判断请求何时完成. 提示词长度另计; 提示词 3 个, 上限 4 个时, 历史最多包含 7 个 token."],
      ["block_hashes", "完整缓存块的链式摘要列表, 类型是 Vec<BlockHash>.", "摘要同时包含当前块与之前的前缀信息, 用于查找相同开头的已缓存页. 已确认输出填满新块时继续延长这条链."],
      ["status", "调度状态, 类型是 RequestStatus.", "Waiting 表示等待分配; Running 表示持有缓存并可执行; Preempted 表示缓存被回收后重新等待. 完成的请求会从队列移除."],
    ],
  },
  queues: {
    title: "预算初始化中的名字",
    intro: "一次 schedule 调用为这一轮创建计划. 一轮可以包含多条请求, 预算计算它们的输入 token 总数.",
    entries: [
      ["self.config", "调度器保存的配置.", "提供每轮 token 上限与同时运行的请求数量上限."],
      ["max_num_batched_tokens", "每轮所有请求的输入 token 总数上限.", "实验配置为 32768. 它限制一轮的计算量, 不限制整条请求的总长度."],
      ["token_budget", "这一轮还可派发的输入数量.", "从配置上限开始, 每派发一个片段就扣除片段长度."],
    ],
  },
  waiting: {
    title: "waiting 队列的字段与局部变量",
    intro: "先从队首取请求, 检查暂停和并发上限, 再查可复用前缀并计算本轮片段. VecDeque 是可从两端操作的队列. FA (full attention, 全注意力) 按位置保存读取历史的数值, 每页覆盖 784 个 token. GDN 保存随输入更新的历史状态, 状态槽是一份状态的存放位置, 快照是指定时刻保存的状态副本. 调度器同时管理这两类缓存, 后面的缓存章节会展开它们的计算方式.",
    entries: [
      ["self.waiting / req", "等待队列, 以及这次从队首取出的 Request.", "pop_front() 取队首; 暂时无法执行时, push_front(req) 将它放回队首."],
      ["self.paused / req.id", "暂时停止推进的请求编号集合, 以及当前请求编号.", "客户端读取过慢时, 输出缓冲区会积压. 暂停集合让调度器跳过这些请求, 保留后续继续的机会."],
      ["paused_waiting", "本轮取出但仍暂停的请求队列.", "暂存这些请求, 让后面的请求有机会被检查; 之后重新接回等待队列."],
      ["self.running / max_num_seqs", "持有缓存的运行队列, 以及可同时运行的请求数上限.", "达到上限就结束新请求接纳, 即使 token_budget 仍有余额."],
      ["self.kv", "Rust 的混合缓存管理器.", "查找前缀缓存, 分配 FA 页与 GDN 状态槽, 并提供块表."],
      ["fa_hit / mb_hit / hit_len", "命中的 FA 页, GDN 快照, 以及两类缓存共同可用的前缀 token 数.", "从 hit_len 开始计算剩余历史. 缓存命中需要可恢复的模型状态, 才能跳过对应的输入."],
      ["total_tokens / remaining", "已确认历史加草稿的长度, 以及扣除命中前缀后的长度.", "num_tokens_with_spec() 将草稿也计入输入; remaining 是本次尚需安排的总量."],
      ["token_budget / to_schedule", "本轮剩余预算, 以及经过块边界调整后的输入数量.", "先取 remaining 与预算中的较小值, 再用 aligned_prefill 选定实际片段. 结果为 0 时结束本轮接纳."],
    ],
  },
  aligned: {
    title: "aligned_prefill 的参数与边界计算",
    intro: "函数接收一个候选输入片段, 返回允许派发的 token 数. usize 的除法在这里是整数除法; saturating_sub() 在被减数较小时返回 0, 避免无符号下溢.",
    entries: [
      ["self / request", "调度器自身, 以及要处理的 Request.", "self 提供缓存块大小和配置; request 提供提示词长度与已确认历史."],
      ["start / count", "本轮在完整历史中的起点, 以及预算初步允许的输入数量.", "候选区间是 [start, start + count). 返回值可因边界约束而缩短."],
      ["request.prompt_len / request.token_ids", "原始提示词长度, 以及已确认历史列表.", "既支持初次提示词计算, 也支持缓存被回收后重算已经生成的历史."],
      ["prefill_end", "需要批量读取或重算的历史区间终点.", "取提示词长度与历史长度减 1 的较大值. 已进入之后的 decode 区间时, 直接沿用 count."],
      ["block / self.kv.block_size()", "缓存块包含的 token 数, 本项目为 784.", "把序列位置换算成完整页边界."],
      ["end / max_num_batched_tokens", "候选区间终点, 以及配置中的每轮输入上限.", "若本轮仍处于未读完的 prefill, 且配置预算至少一页, 就将 end 向下对齐到页边界."],
      ["last_boundary", "已确认历史中最后一个完整页的结束位置.", "历史长度除以 block 再乘 block. 32768 个 token 对应 32144, 因而完整页和后面的 624 个 token 分开处理."],
      ["next_boundary", "start 所在页之后的第一个页边界.", "起点在页中间时, 先安排到这个边界, 便于保存可恢复状态."],
      ["stop", "当前检查的候选边界.", "只有 start < stop < end 时才缩短片段. 边界等于 end 时保留现有长度."],
      ["end.saturating_sub(start)", "调整后的片段长度, 也是函数返回值.", "count 大于 0 时保证至少返回 1, 让较小预算或未对齐位置也能推进."],
    ],
  },
  output: {
    title: "ScheduledRequest 的 6 个字段",
    intro: "这是 worker 对一条请求在本轮的执行视图. 和长期保存的 Request 相比, 它只携带这轮计算所需的数据与缓存地址.",
    entries: [
      ["request_id", "对应 Request.id 的请求编号.", "让 worker 找到自己的请求历史, 并让 Rust 对应返回结果."],
      ["token_ids", "本轮实际要计算的输入 ID 列表.", "它是历史中的一个片段, 也可能包含待验证草稿. 第一次分块有 32144 个 ID, 第二次有 624 个."],
      ["prefill_token_ids", "首次接纳或抢占后重算时的完整已确认历史, 类型是 Option<Vec<u32>>.", "Some(history) 让 worker 校验完整历史. 连续执行时传 None, 沿用 worker 已保存的历史."],
      ["num_computed_tokens", "本轮输入在完整请求历史中的起点.", "实际调用方和 Python planner 将它用作绝对位置: 第二块从 32144 开始, 本轮 token_ids 内的下标仍从 0 开始."],
      ["fa_block_table", "按逻辑页顺序排列的 FA 物理页编号列表.", "位置 p 使用列表下标 p / 784 对应的页, 再用 p % 784 找到页内位置. 有效页编号大于 0."],
      ["mamba_block_table", "GDN 状态快照与本轮状态候选的物理槽编号列表.", "源码沿用 Mamba 名称. 0 表示该位置没有保留快照, 写入目标需要有效的正编号. planner 据此选择读写状态."],
    ],
  },
  batchOutput: {
    title: "SchedulerOutput 的 5 个字段",
    intro: "它将一轮的多个 ScheduledRequest 和清理通知组合起来. num_batched_tokens 是本轮输入量, cache_hit_tokens 是调度器记录的缓存命中量.",
    entries: [
      ["scheduled", "按调度顺序排列的 ScheduledRequest 列表.", "worker 遍历它并组合成一批模型输入. 只包含本轮真正执行的请求."],
      ["finished_request_ids", "本轮通知 worker 清理的已完成请求编号.", "worker 删除对应历史, 采样器与缓存状态记录, 结束这条请求的资源生命周期."],
      ["preempted_request_ids", "本轮被回收缓存, 需要重新排队的请求编号.", "worker 清除旧的计算位置与 GDN 状态来源, 避免重用已经失效的地址."],
      ["num_batched_tokens", "scheduled 中所有 token_ids 的长度之和.", "worker 重新计算这个和, 检查 Rust 发来的数量是否与实际列表一致."],
      ["cache_hit_tokens", "调度器记录的本轮新接纳请求前缀命中总量.", "用于统计已经由缓存覆盖的输入; 它是 Rust 侧统计字段, Python SchedulerOutput 不携带它."],
    ],
  },
  workerResult: {
    title: "WorkerOutput 与 RequestOutput 的字段",
    intro: "WorkerOutput 是一轮返回消息. 其中每个 RequestOutput 保存一条请求的确认结果. 普通生成时接受草稿数为 0, 新草稿列表为空.",
    entries: [
      ["outputs", "WorkerOutput 中这一轮各请求的 RequestOutput 列表.", "Python 可按计算阶段重排请求, Rust 按 request_id 对应结果与调度请求. 每个已调度请求都有一个结果项, 包括输出为空的中间 prefill."],
      ["request_id", "结果所属的请求编号.", "Rust 用它查找运行中的 Request, 并检查重复或未知结果."],
      ["token_ids", "本轮确认的输出 ID 列表.", "中间 prefill 返回空列表. 最后一块或普通 decode 返回 1 个; MTP 可包含被接受的草稿和一个后续 token."],
      ["num_accepted_draft_tokens", "本轮被目标模型接受的草稿数量.", "确认多少草稿, 就保留多少对应缓存进度. 普通生成取 0."],
      ["new_draft_token_ids", "供下一轮验证的新 MTP 草稿列表.", "Rust 将它们装入 Request.draft_token_ids, 用于下一轮输入预算和验证. 普通生成为空."],
    ],
  },
  worker: {
    title: "execute_model 入口中的消息字段与状态",
    intro: "这段 Python 代码先处理清理通知, 再核对输入数量. SchedulerOutput 是调度消息; WorkerOutput 是返回消息. MTP 控制器保存草稿相关状态.",
    entries: [
      ["scheduled / scheduled.scheduled", "函数接收的一轮消息, 以及其中本轮执行的请求列表.", "消息对象与内部列表名称相近. 内部列表的每项是 ScheduledRequest."],
      ["finished_request_ids / rid", "需要清理的请求编号列表, 以及循环当前处理的编号.", "unregister_request(rid) 删除 worker 保存的历史, 采样器和状态记录."],
      ["preempted_request_ids", "缓存被回收, 即将重新排队的请求编号.", "清掉旧缓存位置, 保留请求历史供之后重新计算."],
      ["self.mtp", "MTP 控制器, 关闭 MTP 时为 None.", "forget(rid) 清除该请求的草稿相关状态, 避免继续使用被回收的状态."],
      ["self.sources", "请求编号到最近已提交 GDN 状态槽的映射.", "状态槽是 GPU 状态数组中的一行. 抢占时删除旧映射, 重算时重新选择起点."],
      ["self.computed", "worker 为各请求保存的已提交计算位置映射.", "和 Rust 的 num_computed_tokens 对照. 抢占后旧位置失效, 因此删除."],
      ["num_batched_tokens / r.token_ids", "消息宣告的总输入量, 以及一条计划中的实际输入列表.", "sum(len(...)) 重新求和. 数量不相等时抛出 ValueError, 在执行模型前拒绝错误计划."],
    ],
  },
  plan: {
    title: "plan_request 的参数与检查变量",
    intro: "planner 是在 CPU 上整理执行计划的函数. PlannedRequest 返回本轮应读取的 GDN 状态槽, 各输入的写入目标和采样位置, 供模型计算使用.",
    entries: [
      ["request", "本轮的 ScheduledRequest.", "提供输入 ID, 历史起点和 FA / GDN 地址表."],
      ["history", "worker 保存的完整已确认 token 历史.", "用于核对本轮输入是否真的是这条历史从 start 开始的片段."],
      ["source", "上一轮已提交的 GDN 状态槽编号, 或 None.", "None 表示首次接纳或重新接纳, 需要从零状态或命中前缀快照选取起点."],
      ["fa_capacity / mamba_capacity", "FA 页池与 GDN 状态池的编号容量, 包含保留的 0 号位置.", "地址必须小于容量. 两个池分别检查, 防止用一类缓存的容量验证另一类缓存."],
      ["speculative_tokens", "允许输入的 MTP 草稿数量, 当前支持 0 或 4.", "0 表示普通生成. 限制草稿长度并检查验证输入是否包含正确的已确认起点."],
      ["start / tokens / end", "历史起点, 本轮输入列表, 以及起点加输入长度得到的终点.", "本轮区间为 [start, end). 输入必须非空, 起点必须落在已确认历史中."],
      ["known", "本轮输入中可从已确认历史核对的 token 数.", "先核对 tokens[:known] 与 history 的对应片段, 剩余部分才视为草稿."],
      ["drafts", "本轮输入超过已确认历史的待验证候选.", "检查长度是否超过 speculative_tokens. 带草稿时, 已确认输入恰有一个, 为验证提供起点."],
      ["admission", "source is None 的判断结果.", "区分首次接纳或重算接纳, 与已有状态可连续推进的请求."],
    ],
  },
  validate: {
    title: "返回数量检查中的字段与变量",
    intro: "Rust 在修改请求之前检查 worker 结果. 本节普通生成的 num_accepted_draft_tokens 为 0, 因而最终片段期望 1 个输出, 中间片段期望 0 个.",
    entries: [
      ["req / result", "运行中的 Request, 以及对应的 RequestOutput.", "分别提供执行前的历史与 worker 确认的结果."],
      ["scheduled_end", "本轮起点加 num_in_flight_tokens 得到的候选结束位置.", "判断这一轮是否覆盖提示词或已确认历史的末尾."],
      ["req.token_ids / req.prompt_len", "已确认历史与原始提示词长度.", "用两者长度的较大值确定当前需要读到的末尾."],
      ["final_chunk / expected", "是否为最终片段, 以及期望返回的输出数量.", "最终片段期望接受的草稿数加 1, 中间片段期望 0."],
      ["result.num_accepted_draft_tokens / result.token_ids", "被接受的草稿数量, 以及这轮确认的输出列表.", "用列表实际长度与 expected 比较, 防止 worker 多返回或少返回 token."],
      ["UpdateError / request_id / reason / id", "校验错误记录, 其中的请求编号和原因, 以及当前编号变量.", "数量错误时返回 wrong verified token count, 让上层处理错误并保留尚未被修改的请求状态."],
    ],
  },
  commit: {
    title: "提交结果中的字段与操作",
    intro: "本段在返回消息已经通过校验后执行. 提交是把临时计算结果确认为下一轮可使用的请求状态.",
    entries: [
      ["req.num_computed_tokens / scheduled_end", "已提交缓存位置, 以及本轮候选结束位置.", "普通生成时直接推进到 scheduled_end. MTP 还需要扣掉候选草稿, 再加回已接受部分."],
      ["scheduled_drafts / result.num_accepted_draft_tokens", "本轮实际计算的草稿数量, 以及通过验证的草稿数量.", "只保留被确认的缓存进度. 当前普通生成示例中两者都为 0."],
      ["req.num_in_flight_tokens", "尚未提交的本轮输入计数.", "提交完成后清零, 表示这一轮已结清."],
      ["result.token_ids / req.max_tokens / req.num_generated_tokens()", "确认的输出列表, 允许生成的上限, 以及已生成的数量.", "saturating_sub() 求剩余额度; truncate() 将输出裁到这个额度, 避免超过用户的输出限制."],
      ["token / req.is_finished() / req.append_token(token)", "当前输出 ID, 是否已达到输出上限的判断, 以及追加操作.", "逐个追加到已确认历史. 达到上限就停止循环; 新追加的最后一个 token 由之后的 decode 计算缓存."],
      ["req.draft_token_ids.clear()", "清空请求保存的旧草稿列表.", "旧草稿本轮已经完成验证. 后续代码再安装 worker 提供的新草稿; 普通生成仍为空."],
    ],
  },
};
