export const specifications = {
  request: ["crates/scheduler/src/request.rs", "pub struct Request {", "\nimpl Request {"],
  tokenHistory: ["crates/scheduler/src/request.rs", "    pub token_ids: Vec<u32>,", "    /// Unverified MTP draft tokens appended"],
  computedCounters: ["crates/scheduler/src/request.rs", "    pub num_computed_tokens: usize,", "    /// Maximum number of output tokens"],
  aligned: ["crates/scheduler/src/lib.rs", "    fn aligned_prefill(", "    pub fn new("],
  queues: ["crates/scheduler/src/lib.rs", "        let mut token_budget", "        let mut still_running"],
  waiting: ["crates/scheduler/src/lib.rs", "        // ── phase 2:", "            let has_running"],
  output: ["crates/scheduler/src/output.rs", "pub struct ScheduledRequest", "// ── step output"],
  batchOutput: ["crates/scheduler/src/output.rs", "pub struct SchedulerOutput", "// ── worker feedback"],
  workerResult: ["crates/scheduler/src/output.rs", "pub struct WorkerOutput", null],
  validate: ["crates/scheduler/src/lib.rs", "            let final_chunk", "            let computed_after"],
  commit: ["crates/scheduler/src/lib.rs", "            req.num_computed_tokens =\n", "            let full_blocks"],
  worker: ["python/oh_my_vllm/worker/model_runner.py", "    def execute_model(", "        plans = []"],
  plan: ["python/oh_my_vllm/worker/batch_plan.py", "def plan_request(", null, 24],
  runtimeConfig: ["python/oh_my_vllm/worker/model_runner.py", "class RuntimeConfig:", "\n\nclass OhMyVllmWorker"],
  batchFields: ["python/oh_my_vllm/models/qwen.py", "class AttentionBatch:", "    def delta("],
  poolTouch: ["crates/kv-cache/src/pool.rs", "    pub fn touch(", "    /// Release one reference"],
  protocolResult: ["python/oh_my_vllm/worker/protocol.py", "class RequestOutput:", "\n\n@dataclass\nclass WorkerOutput"],
  modelForward: ["python/oh_my_vllm/models/qwen.py", "    def forward(\n", "    def draft("],
  modelFA: ["python/oh_my_vllm/models/qwen.py", "    def full_attention(\n", "    def delta_attention("],
  modelGDN: ["python/oh_my_vllm/models/qwen.py", "    def delta_attention(\n", "    def forward_residual("],
  samplingParams: ["python/oh_my_vllm/worker/sampling.py", "class SamplingParams:", "    def __post_init__("],
  verifyRows: ["python/oh_my_vllm/worker/sampler.py", "def verify_rows(", "\n\nclass RequestSampler"],
  graphReplay: ["python/oh_my_vllm/worker/decode_graph.py", "    def replay(\n", "\n\nclass DraftGraph"],
  irDispatch: ["python/oh_my_vllm/ir/core.py", "    def __call__(self, *args:", "\n\ndef operations("],
  measurement: ["benchmarks/ttft.py", "def summarize(", "\n\ndef compare("],
  wireInit: ["crates/zmq-worker/src/protocol.rs", "pub struct InitMsg {", "\n#[derive(Debug, Serialize)]\npub struct RegisterMsg"],
  wireExecute: ["crates/zmq-worker/src/protocol.rs", "pub struct ExecuteMsg {", "\n#[derive(Debug, Serialize)]\npub struct ScheduledRequestMsg"],
};
