export const sourceNotes = {
  gatedLinear: {
    title: "门控归一化投影的五个输入", intro: "每个 GDN 头有 128 个值, 刚好组成一个 FP8 scale 分组. 融合先将带 SiLU 门的 RMS 结果舍入为 BF16, 再量化这一结果.",
    entries: [
      ["x", "GDN 输出, BF16 [行数, 48, 128].", "每个头独立计算均方根, token 行可以来自 packed 视图."],
      ["gamma", "128 个 FP32 RMS 乘数.", "所有头使用相同的逐维权重, checkpoint.norm 用 offset=False 读取原权重."],
      ["gate", "BF16 [行数, 48, 128] 输出门.", "来自 QKVZ 的 z 部分, 其 SiLU 值乘到归一化结果上."],
      ["weight", "FP8 [输出列数, 6144] checkpoint 权重.", "把 48 个头合并为 6144 维, 再投影到目标隐藏维度 5120."],
      ["scale", "FP32 [输出列数/128, 48] checkpoint scale.", "每项对应 128x128 权重块, 与每行 128 元素的激活 scale 一同用于 GEMM."],
      ["_GATED_OP", "gated_norm_fp8_linear 的语义操作对象.", "返回独立且连续的 BF16 [行数, 输出列数] 张量."],
    ],
  },
  normalizedLinear: {
    title: "融合投影的特征, 权重与 scale", intro: "残差相加先舍入为 BF16, RMS 在 FP32 归约, 归一化结果再舍入为 BF16. 量化使用这一舍入后的值, 两份输出都有独立存储.",
    entries: [
      ["x", "当前计算分支的 BF16 [行数, 5120] 特征.", "与先前残差相加, 得到进入 MLP 的完整特征."],
      ["residual", "相同形状的 BF16 累积残差.", "融合操作返回新的残差和, 下一层继续使用."],
      ["gamma", "5120 个 FP32 RMS 乘数.", "逐列调节归一化值; 加载时已包含 norm 权重的 offset."],
      ["weight", "FP8 [输出列数, 5120] 投影权重.", "MLP 的 gate/up 合并为 34816 列."],
      ["scale", "FP32 [输出列数/128, 40] 权重缩放系数.", "每项对应权重的 128x128 块, 与激活的每行 128 元素 scale 一起用于 GEMM."],
      ["_OP", "add_norm_fp8_linear 的语义操作对象.", "选择 native 数学参考或当前 CUDA / TileLang provider, 返回残差和与 BF16 投影."],
    ],
  },
  tokenHistory: {
    title: "token_ids: 请求的 token 历史",
    intro: "这是 Request 记录中的一个字段. 这里的列表保存提示词和已经确认的输出, 每个整数对应词表中的一个片段.",
    entries: [["token_ids", "按顺序保存的 token ID 列表, 类型是 Vec<u32>.", "模型读取这些 ID. 生成被确认后, 新 ID 加到列表末尾, 供后续计算使用."]],
  },
  computedCounters: {
    title: "两个计算进度字段",
    intro: "缓存保存模型已经算出的中间结果, 供下一轮复用. 注释中的 KV 是 key/value, 即模型用来读取历史的两组数值. GDN 将历史信息逐步汇入一个状态, 源码沿用 Mamba 名称. 本项目将历史按每块 784 个 token 管理, align-mode 表示在选定块边界保存可恢复的 GDN 状态. 计数表示这两类缓存共同可用的进度.",
    entries: [
      ["num_computed_tokens", "已提交且缓存可用的 token 数, 也是下一轮输入的起点.", "已提交 2 个 token 时, 下一轮从历史下标 2 开始. worker 的结果确认后才推进这个计数."],
      ["num_in_flight_tokens", "本轮已经派发, 尚未提交的输入 token 数.", "派发 1 个输入时为 1. Rust 检查返回结果后, 将它计入已提交进度并清零此字段."],
    ],
  },
  request: {
    title: "Request 的 9 个字段",
    intro: "Request 是 Rust 为一条请求保存的状态记录. RequestId 标识请求, BlockHash 保存前缀摘要. 块是固定长度的历史片段, 本项目每块 784 个 token; 前缀摘要用于查找这些片段的缓存. MTP (Multi-Token Prediction) 先提出多个候选 token, 再由目标模型验证; 尚待验证的候选叫作草稿.",
    entries: [
      ["id", "这条请求的唯一编号, 类型是 RequestId.", "把调度计划, 缓存分配, worker 返回结果和取消操作对应到同一条请求."],
      ["prompt_len", "最初提示词的 token 数, 请求创建时确定.", "即使历史继续增长也保留原值. token_ids.len() 减去它, 得到已生成的 token 数."],
      ["token_ids", "完整的已确认历史: 提示词加上已确认的输出 ID.", "用于选择本轮输入和保存生成结果. 示例 [17, 92, 6] 加入输出 42 后成为 [17, 92, 6, 42]."],
      ["draft_token_ids", "MTP 提出的待验证 token ID 列表.", "调度时将草稿计入输入预算. worker 返回后清空旧草稿, 再安装下一轮草稿. 普通生成时为空."],
      ["num_computed_tokens", "已经提交, 且模型缓存可用的历史前缀长度.", "决定下一轮从哪个位置开始计算. 新请求通常为 0, 命中可复用前缀时可从命中位置开始."],
      ["num_in_flight_tokens", "最近一轮已发给 worker, 尚未提交的输入数量.", "校验返回结果并计算本轮结束位置. 派发后增加, 确认后清零, 防止把在途计算提前当成可用缓存."],
      ["max_tokens", "允许生成的输出 token 数上限.", "限制输出历史的增长并判断请求何时完成. 提示词长度另计; 提示词 3 个, 上限 4 个时, 历史最多包含 7 个 token."],
      ["block_hashes", "完整缓存块的链式摘要列表, 类型是 Vec<BlockHash>.", "摘要同时包含当前块与之前的前缀信息, 用于查找相同开头的已缓存页. 已确认输出填满新块时继续延长这条链."],
      ["status", "调度状态, 类型是 RequestStatus.", "Waiting 表示等待分配; Running 表示持有缓存并可执行; Preempted 表示缓存被回收后重新等待. 完成的请求会从队列移除."],
    ],
  },
  queues: {
    title: "预算初始化中的名字",
    intro: "一次 schedule 调用为这一轮创建计划. 一轮可以包含多条请求, 预算计算它们的输入 token 总数.",
    entries: [
      ["self.config", "调度器保存的配置.", "提供每轮 token 上限与同时运行的请求数量上限."],
      ["max_num_batched_tokens", "每轮所有请求的输入 token 总数上限.", "实验配置为 32768. 它限制一轮的计算量, 不限制整条请求的总长度."],
      ["token_budget", "这一轮还可派发的输入数量.", "从配置上限开始, 每派发一个片段就扣除片段长度."],
      ["has_prefill_chunk", "本轮已成功分配至少一页 prefill 片段的标记.", "只有实际分配后才设为 true. decode 或草稿验证输入不会设置该标记, 只有这类输入的轮次让小片段继续推进."],
    ],
  },
  waiting: {
    title: "waiting 队列的字段与局部变量",
    intro: "先从队首取请求, 检查暂停和并发上限, 再查可复用前缀并计算本轮片段. FA (full attention, 全注意力) 按位置保存读取历史的数值, 每页覆盖 784 个 token. GDN 保存随输入更新的历史状态, 状态槽是一份状态的存放位置, 快照是指定时刻保存的状态副本. 调度器同时管理这两类缓存, 后面的缓存章节会展开它们的计算方式.",
    entries: [
      ["self.waiting / req", "等待队列, 以及这次从队首取出的 Request.", "保持先来先服务的顺序. 暂时无法执行时放回队首, 下一轮继续检查."],
      ["self.paused / req.id", "暂时停止推进的请求编号集合, 以及当前请求编号.", "客户端读取过慢时, 输出缓冲区会积压. 暂停集合让调度器跳过这些请求, 保留后续继续的机会."],
      ["paused_waiting", "本轮取出但仍暂停的请求队列.", "暂存这些请求, 让后面的请求有机会被检查; 之后重新接回等待队列."],
      ["self.running / max_num_seqs", "持有缓存的运行队列, 以及可同时运行的请求数上限.", "达到上限就结束新请求接纳, 即使 token_budget 仍有余额."],
      ["self.kv", "Rust 的混合缓存管理器.", "查找前缀缓存, 分配 FA 页与 GDN 状态槽, 并提供块表."],
      ["fa_hit / mb_hit / hit_len", "命中的 FA 页, GDN 快照, 以及两类缓存共同可用的前缀 token 数.", "从 hit_len 开始计算剩余历史. 缓存命中需要可恢复的模型状态, 才能跳过对应的输入."],
      ["total_tokens / remaining", "已确认历史加草稿的长度, 以及扣除命中前缀后的长度.", "num_tokens_with_spec() 将草稿也计入输入; remaining 是本次尚需安排的总量."],
      ["token_budget / to_schedule", "本轮剩余预算, 以及经过块边界调整后的输入数量.", "先取 remaining 与预算中的较小值, 再用 aligned_prefill 选定实际片段. 结果为 0 时结束本轮接纳."],
      ["has_prefill_chunk / prefill_end", "本轮已分配整页 prefill 的标记, 以及需批量计算的历史终点.", "满足 defer_aligned_prefill 条件时将当前请求放回队首. 成功分配整页片段后才更新标记."],
    ],
  },
  aligned: {
    title: "aligned_prefill 的参数与边界计算",
    intro: "函数将候选输入片段调整到可恢复的缓存边界, 返回本轮允许派发的 token 数.",
    entries: [
      ["self / request", "调度器自身, 以及要处理的 Request.", "self 提供缓存块大小和配置; request 提供提示词长度与已确认历史."],
      ["start / count", "本轮在完整历史中的起点, 以及预算初步允许的输入数量.", "候选区间是 [start, start + count). 返回值可因边界约束而缩短."],
      ["request.prompt_len / request.token_ids", "原始提示词长度, 以及已确认历史列表.", "既支持初次提示词计算, 也支持缓存被回收后重算已经生成的历史."],
      ["prefill_end", "需要批量读取或重算的历史区间终点.", "取提示词长度与历史长度减 1 的较大值. 已进入之后的 decode 区间时, 直接沿用 count."],
      ["block / self.kv.block_size()", "缓存块包含的 token 数, 本项目为 784.", "把序列位置换算成完整页边界."],
      ["end / max_num_batched_tokens", "候选区间终点, 以及配置中的每轮输入上限.", "若本轮仍处于未读完的 prefill, 且配置预算至少一页, 就将 end 向下对齐到页边界."],
      ["last_boundary", "已确认历史中最后一个完整页的结束位置.", "历史长度除以 block 再乘 block. 32768 个 token 对应 32144, 因而完整页和后面的 624 个 token 分开处理."],
      ["next_boundary", "start 所在页之后的第一个页边界.", "起点在页中间时, 先安排到这个边界, 便于保存可恢复状态."],
      ["stop", "当前检查的候选边界.", "只有 start < stop < end 时才缩短片段. 边界等于 end 时保留现有长度."],
      ["end.saturating_sub(start)", "调整后的片段长度, 也是函数返回值.", "count 大于 0 时保证至少返回 1, 让较小预算或未对齐位置也能推进."],
    ],
  },
  deferredPrefill: {
    title: "何时延后对齐产生的单行 prefill", intro: "先选片段, 再决定是否在下一轮执行. 判断发生在缓存分配前, 因而等待请求此时不占 FA 页或 GDN 槽.",
    entries: [
      ["self / request", "调度器与当前请求.", "提供每轮预算上限, 页大小, 原始提示词和已确认历史."],
      ["start / count", "输入片段的绝对起点与 aligned_prefill 返回的长度.", "count 为 1 时才可能延后, 草稿验证和 decode 仍按各自的历史区间推进."],
      ["budget", "本轮尚可使用的输入行数.", "与剩余 prefill 长度和下一页边界比较, 判断本轮能否到达恢复点或结束提示词."],
      ["has_prefill_chunk", "本轮已成功分配至少一页 prefill 的布尔标记.", "它为 true 时才考虑延后. 纯 decode, 草稿验证和此前的小片段都保留正输入推进."],
      ["block / prefill_end", "每页 token 数与批量计算历史的终点.", "prefill_end 取 prompt_len 与已确认历史长度减 1 的较大值, 同时支持抢占重算."],
      ["block - start % block", "从起点到下一页边界所需的 token 数.", "预算不足这段距离, 且本轮无法完成 prefill 时, 一行片段留到下一轮."],
    ],
  },
  output: {
    title: "ScheduledRequest 的 6 个字段",
    intro: "这是 worker 对一条请求在本轮的执行视图. 和长期保存的 Request 相比, 它只携带这轮计算所需的数据与缓存地址.",
    entries: [
      ["request_id", "对应 Request.id 的请求编号.", "让 worker 找到自己的请求历史, 并让 Rust 对应返回结果."],
      ["token_ids", "本轮实际要计算的输入 ID 列表.", "它是历史中的一个片段, 也可能包含待验证草稿. 第一次分块有 32144 个 ID, 第二次有 624 个."],
      ["prefill_token_ids", "首次接纳或抢占后重算时的完整已确认历史, 类型是 Option<Vec<u32>>.", "Some(history) 让 worker 校验完整历史. 连续执行时传 None, 沿用 worker 已保存的历史."],
      ["num_computed_tokens", "本轮输入在完整请求历史中的起点.", "实际调用方和 Python planner 将它用作绝对位置: 第二块从 32144 开始, 本轮 token_ids 内的下标仍从 0 开始."],
      ["fa_block_table", "按逻辑页顺序排列的 FA 物理页编号列表.", "位置 p 使用列表下标 p / 784 对应的页, 再用 p % 784 找到页内位置. 有效页编号大于 0."],
      ["mamba_block_table", "GDN 状态快照与本轮状态候选的物理槽编号列表.", "源码沿用 Mamba 名称. 0 表示该位置没有保留快照, 写入目标需要有效的正编号. planner 据此选择读写状态."],
    ],
  },
  batchOutput: {
    title: "SchedulerOutput 的 5 个字段",
    intro: "它将一轮的多个 ScheduledRequest 和清理通知组合起来. num_batched_tokens 是本轮输入量, cache_hit_tokens 是调度器记录的缓存命中量.",
    entries: [
      ["scheduled", "按调度顺序排列的 ScheduledRequest 列表.", "worker 遍历它并组合成一批模型输入. 只包含本轮真正执行的请求."],
      ["finished_request_ids", "本轮通知 worker 清理的已完成请求编号.", "worker 删除对应历史, 采样器与缓存状态记录, 结束这条请求的资源生命周期."],
      ["preempted_request_ids", "本轮被回收缓存, 需要重新排队的请求编号.", "worker 清除旧的计算位置与 GDN 状态来源, 避免重用已经失效的地址."],
      ["num_batched_tokens", "scheduled 中所有 token_ids 的长度之和.", "worker 重新计算这个和, 检查 Rust 发来的数量是否与实际列表一致."],
      ["cache_hit_tokens", "调度器记录的本轮新接纳请求前缀命中总量.", "用于统计已经由缓存覆盖的输入; 它是 Rust 侧统计字段, Python SchedulerOutput 不携带它."],
    ],
  },
  workerResult: {
    title: "WorkerOutput 与 RequestOutput 的字段",
    intro: "WorkerOutput 是一轮返回消息. 其中每个 RequestOutput 保存一条请求的确认结果. 普通生成时接受草稿数为 0, 新草稿列表为空.",
    entries: [
      ["outputs", "WorkerOutput 中这一轮各请求的 RequestOutput 列表.", "Python 可按计算阶段重排请求, Rust 按 request_id 对应结果与调度请求. 每个已调度请求都有一个结果项, 包括输出为空的中间 prefill."],
      ["request_id", "结果所属的请求编号.", "Rust 用它查找运行中的 Request, 并检查重复或未知结果."],
      ["token_ids", "本轮确认的输出 ID 列表.", "中间 prefill 返回空列表. 最后一块或普通 decode 返回 1 个; MTP 可包含被接受的草稿和一个后续 token."],
      ["num_accepted_draft_tokens", "本轮被目标模型接受的草稿数量.", "确认多少草稿, 就保留多少对应缓存进度. 普通生成取 0."],
      ["new_draft_token_ids", "供下一轮验证的新 MTP 草稿列表.", "Rust 将它们装入 Request.draft_token_ids, 用于下一轮输入预算和验证. 普通生成为空."],
    ],
  },
  worker: {
    title: "execute_model 入口中的消息字段与状态",
    intro: "execute_model 使用 torch.inference_mode 关闭梯度记录, 减少推理中的自动求导开销. 入口先处理清理通知, 再核对输入数量. SchedulerOutput 是调度消息; WorkerOutput 是返回消息. MTP 控制器保存草稿相关状态.",
    entries: [
      ["scheduled / scheduled.scheduled", "函数接收的一轮消息, 以及其中本轮执行的请求列表.", "消息对象与内部列表名称相近. 内部列表的每项是 ScheduledRequest."],
      ["finished_request_ids / rid", "需要清理的请求编号列表, 以及循环当前处理的编号.", "unregister_request(rid) 删除 worker 保存的历史, 采样器和状态记录."],
      ["preempted_request_ids", "缓存被回收, 即将重新排队的请求编号.", "清掉旧缓存位置, 保留请求历史供之后重新计算."],
      ["self.mtp", "MTP 控制器, 关闭 MTP 时为 None.", "forget(rid) 清除该请求的草稿相关状态, 避免继续使用被回收的状态."],
      ["self.sources", "请求编号到最近已提交 GDN 状态槽的映射.", "状态槽是 GPU 状态数组中的一行. 抢占时删除旧映射, 重算时重新选择起点."],
      ["self.computed", "worker 为各请求保存的已提交计算位置映射.", "和 Rust 的 num_computed_tokens 对照. 抢占后旧位置失效, 因此删除."],
      ["num_batched_tokens / r.token_ids", "消息宣告的总输入量, 以及一条计划中的实际输入列表.", "sum(len(...)) 重新求和. 数量不相等时抛出 ValueError, 在执行模型前拒绝错误计划."],
    ],
  },
  plan: {
    title: "plan_request 的参数与检查变量",
    intro: "planner 是在 CPU 上整理执行计划的函数. PlannedRequest 返回本轮应读取的 GDN 状态槽, 各输入的写入目标和采样位置, 供模型计算使用.",
    entries: [
      ["request", "本轮的 ScheduledRequest.", "提供输入 ID, 历史起点和 FA / GDN 地址表."],
      ["history", "worker 保存的完整已确认 token 历史.", "用于核对本轮输入是否真的是这条历史从 start 开始的片段."],
      ["source", "上一轮已提交的 GDN 状态槽编号, 或 None.", "None 表示首次接纳或重新接纳, 需要从零状态或命中前缀快照选取起点."],
      ["fa_capacity / mamba_capacity", "FA 页池与 GDN 状态池的编号容量, 包含保留的 0 号位置.", "地址必须小于容量. 两个池分别检查, 防止用一类缓存的容量验证另一类缓存."],
      ["speculative_tokens", "允许输入的草稿数量, 支持 0, 4 或 7.", "0 普通生成, 4 为 MTP, 7 为 DSpark; 检查草稿长度与确认起点."],
      ["start / tokens / end", "历史起点, 本轮输入列表, 以及起点加输入长度得到的终点.", "本轮区间为 [start, end). 输入必须非空, 起点必须落在已确认历史中."],
      ["known", "本轮输入中可从已确认历史核对的 token 数.", "先核对 tokens[:known] 与 history 的对应片段, 剩余部分才视为草稿."],
      ["drafts", "本轮输入超过已确认历史的待验证候选.", "检查长度是否超过 speculative_tokens. 带草稿时, 已确认输入恰有一个, 为验证提供起点."],
      ["admission", "source is None 的判断结果.", "区分首次接纳或重算接纳, 与已有状态可连续推进的请求."],
    ],
  },
  validate: {
    title: "返回数量检查中的字段与变量",
    intro: "Rust 在修改请求之前检查 worker 结果. 本节普通生成的 num_accepted_draft_tokens 为 0, 因而最终片段期望 1 个输出, 中间片段期望 0 个.",
    entries: [
      ["req / result", "运行中的 Request, 以及对应的 RequestOutput.", "分别提供执行前的历史与 worker 确认的结果."],
      ["scheduled_end", "本轮起点加 num_in_flight_tokens 得到的候选结束位置.", "判断这一轮是否覆盖提示词或已确认历史的末尾."],
      ["req.token_ids / req.prompt_len", "已确认历史与原始提示词长度.", "用两者长度的较大值确定当前需要读到的末尾."],
      ["final_chunk / expected", "是否为最终片段, 以及期望返回的输出数量.", "最终片段期望接受的草稿数加 1, 中间片段期望 0."],
      ["result.num_accepted_draft_tokens / result.token_ids", "被接受的草稿数量, 以及这轮确认的输出列表.", "用列表实际长度与 expected 比较, 防止 worker 多返回或少返回 token."],
      ["UpdateError / request_id / reason / id", "校验错误记录, 其中的请求编号和原因, 以及当前编号变量.", "数量错误时返回 wrong verified token count, 让上层处理错误并保留尚未被修改的请求状态."],
    ],
  },
  commit: {
    title: "提交结果中的字段与操作",
    intro: "本段在返回消息已经通过校验后执行. 提交是把临时计算结果确认为下一轮可使用的请求状态.",
    entries: [
      ["req.num_computed_tokens / scheduled_end", "已提交缓存位置, 以及本轮候选结束位置.", "普通生成时直接推进到 scheduled_end. MTP 还需要扣掉候选草稿, 再加回已接受部分."],
      ["scheduled_drafts / result.num_accepted_draft_tokens", "本轮实际计算的草稿数量, 以及通过验证的草稿数量.", "只保留被确认的缓存进度. 当前普通生成示例中两者都为 0."],
      ["req.num_in_flight_tokens", "尚未提交的本轮输入计数.", "提交完成后清零, 表示这一轮已结清."],
      ["result.token_ids / req.max_tokens / req.num_generated_tokens()", "确认的输出列表, 允许生成的上限, 以及已生成的数量.", "按剩余输出额度裁剪确认结果, 保证输出数量不超过用户的限制."],
      ["token / req.is_finished() / req.append_token(token)", "当前输出 ID, 是否已达到输出上限的判断, 以及追加操作.", "逐个追加到已确认历史. 达到上限就停止循环; 新追加的最后一个 token 由之后的 decode 计算缓存."],
      ["req.draft_token_ids.clear()", "清空请求保存的旧草稿列表.", "旧草稿本轮已经完成验证. 后续代码再安装 worker 提供的新草稿; 普通生成仍为空."],
    ],
  },
};

Object.assign(sourceNotes, {
  runtimeConfig: {
    title: "RuntimeConfig 的 8 个字段", intro: "这是 Python 接收的启动配置. FA 页数与 GDN 状态槽数包含保留的 0 号位置, 可写容量各少一个.",
    entries: [
      ["model", "本地模型目录.", "读取配置, safetensors, tokenizer 和对话模板."],
      ["max_model_len", "提示词加输出的 token 数上限, 默认 65536.", "校验请求与位置; 长上下文验收使用显式配置, 最高 262144."],
      ["num_gpu_blocks", "兼容现有配置的缓存容量单位, 默认 1024.", "逻辑 FA 页数为它的整数三分之一. 每个逻辑页实际覆盖 784 个 token."],
      ["speculative_tokens", "每轮最大草稿数量, 默认 0.", "0 走普通生成, 4 启用 MTP, 7 使用独立 DSpark; 与显式模式一起校验."],
      ["mamba_blocks", "独立 GDN 状态池容量, 默认 None.", "给定数值时与 FA 分池; None 时采用 FA 逻辑容量."],
      ["speculative_mode", "none, mtp 或 dspark 模式.", "缺省保留旧的 0/4 推导, 显式 dspark 必须对应七个候选."],
      ["draft_model", "独立 DSpark checkpoint 目录.", "DSpark 模式需要此路径, 与目标模型目录分开加载."],
      ["dspark_confidence_threshold", "前缀累积接受置信度阈值, 默认 0.2.", "从首项起累计 confidence 低于阈值就停止, 可返回 0 至 7 个草稿; 0 保留全部合法候选供调试."],
    ],
  },
  batchFields: {
    title: "AttentionBatch 与 Batch 的 12 个字段", intro: "Tensor 是多维数组. 每轮将多条请求的输入拼接成 token 行; starts 标出每条请求的区间, 其余向量按请求或 token 行对应.",
    entries: [
      ["positions", "每个 token 在其完整历史中的位置.", "供 RoPE 和因果长度使用, 从 0 开始."],
      ["fa_slots", "每个 token 的 FA 物理写入槽.", "页编号乘 784 再加页内偏移, 负值跳过写入."],
      ["attention", "本轮选定的注意力执行对象.", "提供计划后的页表和 wrapper, 或 decode / MTP 注意力实现."],
      ["starts", "拼接输入中的请求边界向量.", "两条长度为 3 和 1 的输入对应 [0, 3, 4]."],
      ["sequence_ids", "每个 token 对应的批内请求下标.", "卷积核用它找到该 token 的状态读槽和序列起点."],
      ["state_reads", "每请求的 GDN 起始读槽.", "读取上一轮确认的卷积与递归状态; 首次从零槽或前缀快照开始."],
      ["state_writes", "每个 token 的 GDN 候选写槽.", "负值只推进计算; 正值保存候选, 验证后再选正式状态."],
      ["final_state_writes", "每请求本段结束的状态写槽.", "长 prefill 返回最终状态后, index_copy_ 写到这些位置."],
      ["prefill_sequences", "批内位于前面的 prefill 请求数.", "将批切为 prefill 与 decode/验证两部分, 分别调用长序列和递归实现."],
      ["prefill_tokens", "前面 prefill 请求的输入总行数.", "用它切分 Q/K/V; starts 的后半部分减去它后成为局部下标."],
      ["output_indices", "最后 FA 层需要产生完整输出的行下标, 默认 None.", "普通与 DSpark prefill 只为采样行计算 Q, attention 和 MLP; 所有输入行的 K/V 仍写入缓存. None 保留完整路径."],
      ["output_attention", "为这些选中行准备的 DecodeAttention, 默认 None.", "页表逐选中行展开, 因果终点等于该行位置加 1, 与 output_indices 一一对应."],
    ],
  },
  poolTouch: {
    title: "touch 的引用与空闲队列", intro: "命中索引中的页可能已经没有使用者, 仍在可用队列里等待复用. 命中后先摘下该页, 再增加使用者数量.",
    entries: [
      ["self / block_ids", "当前块池与要引用的编号列表.", "每个编号都属于此池, 编号 0 是保留位置."],
      ["id / is_null / ref_cnt", "循环中的块编号, 保留位置标志与对应引用数.", "跳过保留位置; 引用数为 0 时先从空闲队列移除, 然后增加引用."],
      ["free_queue / remove", "编号索引的双向队列与摘除操作.", "保证后续分配不会拿走当前已经命中的页."],
    ],
  },
  protocolResult: {
    title: "Python RequestOutput 的 8 个字段", intro: "结果按 request_id 对应. 计算结果, 可见文字和终止原因一起返回, Rust 再分别交给调度器和 HTTP 输出层.",
    entries: [
      ["request_id", "长期请求编号.", "批内重排后仍可正确匹配 Rust 的请求."],
      ["token_ids", "本轮保留的输出 ID.", "中间 prefill 为空; 普通最终片段通常有一个, MTP 可有多个."],
      ["error", "请求级错误文字, 默认 None.", "终止对应请求, 与导致 worker 整体退出的故障分开处理."],
      ["num_accepted_draft_tokens", "本轮被保留的已接受草稿数.", "推进缓存计数, 与最终新采样的一个 token 分开."],
      ["new_draft_token_ids", "为下一轮提出的候选 ID.", "保留在草稿列表, 下一轮交给目标模型验证."],
      ["text", "本轮已经能安全发送的增量文字.", "经过 UTF-8 解码与 stop 前缀缓冲后交给 Rust 解析器."],
      ["finish_reason", "终止原因, 未结束时为 None.", "stop 或 length 触发完成事件与状态清理."],
      ["reasoning_tokens", "已产生的推理部分 token 数.", "提供 usage 中的推理数量统计."],
    ],
  },
  modelForward: {
    title: "forward 与 logits 的输入和中间量", intro: "F 是 torch.nn.functional. embedding 按 token ID 查向量. 每层读取对应缓存, 模型层数与缓存数必须一致.",
    entries: [
      ["self / tokens / batch / caches", "模型, 输入 ID 向量, 本轮元数据, 每层的缓存列表.", "tokens 的每行变成 5120 维特征; batch 指定位置与状态读写."],
      ["hidden", "当前层的 token 特征矩阵.", "按层更新; 最后归一化后交给词表投影."],
      ["residual", "延迟相加的残差分支, 初始为 None.", "forward_residual 同时返回新分支与累积残差, 以融合加法和归一化."],
      ["layer / cache / self.layers", "当前层, 该层缓存, 64 层列表.", "一一对应执行 FA 或 GDN 计算."],
      ["self.embedding / self.norm / self.head", "词嵌入矩阵, 最后 RMS 权重, 词表投影矩阵.", "embedding 查输入; norm 整理幅度; head 产生 248320 个词表分数."],
      ["hidden.shape[0] / logits_gemm / F.linear", "输入行数, 小行数投影核, 通用矩阵投影.", "最多 32 行用 CuTe-DSL, 更多行走 F.linear 后转 FP32."],
      ["index / batch.output_indices / self._selected_final", "当前层号, 所需输出行和最后层的选中计算入口.", "第 63 层可保留全部 K/V 并只产生需要的最终特征. 返回数组仍按原输入行寻址, 采样器只读取选中行."],
    ],
  },
  selectedAttention: {
    title: "全部 K/V 与选中输出怎样分别计算", intro: "R 个历史输入都要提供未来 attention 的 K/V, 当前只需要 S 个位置的输出. indices 指定这 S 个位置, 规划在进入编译单元前完成.",
    entries: [
      ["x / residual / normalized", "当前分支, 延迟相加的残差, 归一化输入.", "全部 R 行保留原来的 BF16 舍入, 供 K/V 投影使用."],
      ["cache / batch / indices / output_attention", "持久 KV 池, 位置与写槽, 选中行下标, 相应注意力计划.", "K/V 按全部位置写入, 查询按 indices 的顺序读取相应前缀."],
      ["self.qkv.rows(12288, 14336) / kv / prepare_context", "checkpoint 中的 K/V 权重区间, 投影结果和写入入口.", "2048 列覆盖四个 K 头与四个 V 头, 每头 256 维. 原 FP8 scale 按 128 行完整切片."],
      ["self.qkv.rows(0, 12288) / packed / prepare_query", "Q 与输出门的权重区间, 选中投影和 Q 准备入口.", "只处理 S 行, Q 使用归一化与 RoPE, 其余 256 列提供每头的 gate."],
      ["q / gate / attended / result", "选中查询, 输出门, attention 结果和输出投影.", "24 个 Q 头各有 256 维; sigmoid(gate) 调节 attention, 投影回 5120 维."],
      ["self.mlp_residual / indices.numel()", "选中行的残差与 MLP 路径, 选中行数.", "S 为零时只完成持久 K/V 更新; S 为正时返回 S 行分支与残差."],
    ],
  },
  modelFA: {
    title: "FA 的投影, 门控与缓存", intro: "FA 将输入投影为 Q, K, V 和输出门. Q/K 归一化后应用 RoPE, K/V 写入页式缓存, 门值调节各注意力头的输出.",
    entries: [
      ["self / x / batch / cache", "当前层, 输入特征, 位置和页表计划, 此层 KV 池.", "每个 token 的 5120 维特征变成注意力输出, 页表决定历史来源."],
      ["packed / self.qkv", "合并的投影结果与 FP8 投影权重.", "14336 列包含 Q/门控 12288 列和 K/V 各 1024 列."],
      ["gate", "24 个 Q 头各 256 维的门控.", "从每头 512 列的后 256 列取出, sigmoid 后逐元素调节注意力输出."],
      ["q / self.q_norm / self.k_norm", "准备后的 Q, Q/K 归一化权重.", "prepare_attention 对 Q/K 做 RMS 与 RoPE, 并写 K/V 到缓存."],
      ["out / batch.attention / self.out", "注意力结果, 执行对象, 输出投影.", "读取历史 KV, 乘 gate 后合并头维度, 投影回 5120 维."],
    ],
  },
  modelGDN: {
    title: "GDN 的卷积和递归状态", intro: "Q/K 的 16 个头扩成 48 个值头, 每头 128 维; self.ba 同时产生更新门和衰减参数.",
    entries: [
      ["self / x / batch / cache", "当前层, 输入特征, 状态计划, 两个缓存池.", "用当前输入与已提交状态计算下一特征和候选状态."],
      ["conv_pool / state_pool", "最近三个卷积输入与递归矩阵池.", "源槽提供历史; 写槽保存本段末尾或逐 token 的候选."],
      ["mixed / z / self.qkvz", "合并 Q/K/V, 输出门, 合并投影.", "分别为 10240 和 6144 列; mixed 先经过因果卷积."],
      ["q / k / v", "查询, 键, 值.", "分别拆成 16x128, 16x128, 48x128, 用于递归或长 prefill."],
      ["decay / beta / self.ba", "对数衰减, 更新门, 生成两者的投影.", "delta_gates 使用 A_log 与 dt_bias 计算衰减, sigmoid 计算 beta."],
      ["self.a_log / self.dt_bias / self.conv", "可学习的衰减尺度, 时间偏置, 四位置卷积权重.", "控制历史保持速度与局部输入混合."],
      ["out / self.gate_norm / self.out", "GDN 输出, 带门控 RMS 权重, 输出投影.", "输出按头归一化并乘 SiLU(z), 再投影回 5120 维."],
    ],
  },
  samplingParams: {
    title: "SamplingParams 的 9 个字段", intro: "每条请求保留自己的参数和随机生成器. max_tokens 限制长度, 其余参数控制分数筛选或终止行为.",
    entries: [
      ["max_tokens", "输出 token 上限, 正整数.", "达到数量就结束, 与提示词长度分别计算."],
      ["temperature", "采样温度, 默认 1.", "分数除以温度后做 softmax; 0 走贪心, 极小正值归零."],
      ["top_p", "保留的累计概率阈值, 默认 1.", "按概率从高到低保留直到越过阈值的那一项."],
      ["top_k", "最高分候选数量, 默认 -1.", "-1 或 0 关闭筛选; 正值取第 k 个分数作为阈值, 保留并列."],
      ["seed", "可选的随机种子, 默认 None.", "创建请求自己的 generator, 避免其他请求的采样打乱其随机流."],
      ["ignore_eos", "是否忽略模型 EOS 结束标记, 默认 False.", "基准可固定长度, 普通服务可在 EOS 处结束."],
      ["frequency_penalty", "按已生成出现次数调整分数, 默认 0.", "出现 c 次的 ID 减去 c 乘此参数."],
      ["presence_penalty", "按是否已经生成调整分数, 默认 0.", "已经出现的 ID 减去此参数一次."],
      ["repetition_penalty", "提示词及已生成历史的重复惩罚, 默认 1.", "正分数除以它, 负分数乘以它; 草稿验证逐行加入候选前缀."],
    ],
  },
  verifyRows: {
    title: "verify_rows 的逐行接受规则", intro: "rows 是目标模型对每个前缀的采样结果, drafts 是已有候选. 目标行数应比候选数多一, 最后一行可以给出额外输出.",
    entries: [
      ["rows / drafts", "目标采样行与草稿 ID 列表.", "只有连续匹配的前缀被接受; 第一处不匹配的目标 ID 成为新输出."],
      ["accepted / token / row", "保留列表, 当前目标 ID, 行下标.", "每个可达行先保留目标 ID; 与该位置草稿不等就结束."],
      ["valid / ValueError / RuntimeError", "当前行有效标志, 行数错误与分布无效的错误类型.", "拒绝实际需要访问的无效行; 未到达的后续行不会影响当前接受结果."],
    ],
  },
  graphReplay: {
    title: "replay 更新哪些数据", intro: "CUDA Graph 已记录 kernel 的启动序列和数组地址. 重放前将本轮内容写入固定地址, 保持先复制, 后执行的流顺序.",
    entries: [
      ["self / tokens / batch / tables", "已捕获的图, 当前输入 ID, 元数据, FA 页表.", "图内地址固定, 本轮内容通过 copy_ 更新."],
      ["self.tokens / self.attention.tables", "图的固定输入与固定页表数组.", "复制不同请求的数据, 同一形状仍可重用执行序列."],
      ["self.attention.lengths / batch.positions", "每查询因果终点与历史位置.", "终点等于位置加 1, 保证每个查询只读取自身及之前的 token."],
      ["f / value / fields / getattr", "字段描述, 字段值, dataclass 字段枚举, 按名字取值.", "逐个复制 Tensor 字段, 包括 starts 与状态读写槽."],
      ["self.graph / self.hidden / self.logits", "CUDA Graph, 固定隐藏输出, 固定分数输出.", "replay 执行, 返回共享输出数组供后续采样使用."],
    ],
  },
  irDispatch: {
    title: "语义操作的两条调用路径", intro: "Operation 为同一语义操作提供 eager 执行与编译捕获两条路径. 选择器根据输入的形状, 类型和设备确定具体实现.",
    entries: [
      ["self / args / kwargs", "当前 Operation 与本次调用参数.", "同一语义入口兼容 eager 调用与编译捕获."],
      ["torch.compiler.is_compiling() / self.ir_op", "是否正在捕获图, 与语义节点入口.", "编译时保留语义节点, 由 lowering 选择具体 provider."],
      ["self.select(...).op", "选择器返回的实现入口.", "eager 模式按静态元数据选择并调用, 记录实际选择证据."],
    ],
  },
  measurement: {
    title: "phase_verdict 的两个独立条件", intro: "每个阶段各有五个墙钟时间和五个理论下界. 分别取中位数, 再检查时延倍率与墙钟相对极差.",
    entries: [
      ["wall / lower", "该阶段五次实际秒数和五次理论秒数.", "长度必须都为 5, 每项都是有限正数."],
      ["mode / phase", "推理模式与 prefill / decode 阶段.", "仅 prefix 模式的 prefill 将时延倍率作为报告项."],
      ["median / bound / spread", "墙钟中位数, 下界中位数, 墙钟相对极差.", "倍率使用两个中位数的比值, spread 等于极差除以墙钟中位数."],
      ["wall_median_s / lower_bound_median_s", "两组值各自的中位秒数.", "保留原始量, 使倍率和门槛可以重新核算."],
      ["latency_ratio / wall_spread", "实际与理论中位数的比值和波动比例.", "每个阶段都保留这两项数值."],
      ["latency_gate / latency_passed / spread_passed / passed", "倍率是否作为门槛, 倍率检查结果, 波动检查结果与阶段结果.", "有效倍率门槛最高为 3, 波动最高为 10%. Prefix-hit prefill 只按波动判定, decode 保持两项检查."],
    ],
  },});

Object.assign(sourceNotes, {
  wireInit: {
    title: "InitMsg 的 10 个字段", intro: "Rust 将启动参数编码为 init. Python 检查硬件与页大小约束, 再映射到 RuntimeConfig 并建立模型和缓存.",
    entries: [
      ["model_path", "模型本地目录.", "映射为 RuntimeConfig.model, 从中读取配置, 权重和 tokenizer."],
      ["num_gpu_blocks", "兼容配置的缓存容量单位.", "映射为同名配置, 逻辑 FA 容量取整数三分之一."],
      ["mamba_blocks", "可选独立 GDN 槽容量.", "None 使用 FA 逻辑容量, 数值使用独立池."],
      ["block_size", "每个逻辑页的 token 数.", "固定为 784, 由 Python 核对并据此建立物理布局."],
      ["tensor_parallel_size", "张量并行 GPU 数量.", "当前支持单卡, 固定为 1; Python 拒绝其他数量."],
      ["max_model_len", "提示词加输出的上下文上限.", "用于输入预算与位置检查, 长上下文运行显式配置."],
      ["num_speculative_tokens", "草稿上限.", "映射为 speculative_tokens, 0 普通生成, 4 启用 MTP, 7 启用 DSpark."],
      ["speculative_mode", "可选显式草稿模式.", "映射为同名字段, 缺省兼容旧的 0/4 选择."],
      ["draft_model_path", "独立 DSpark 本地目录.", "映射为 RuntimeConfig.draft_model, 检查配置与权重后加载."],
      ["dspark_confidence_threshold", "前缀累积置信度阈值, 默认 0.2.", "独立自然文本 / 工具历史小样本选定; 首项未达到阈值可返回 0 草稿, 完整负载表现另行测量."],
    ],
  },
  wireRegister: {
    title: "RegisterMsg 的 3 个字段", intro: "离线请求在 Rust 接纳后向 Python 注册. 两侧共享输出预算, 草稿只计算下一轮可以验证的数量.",
    entries: [
      ["request_id", "Rust 分配的请求编号.", "Python 用它保存历史和采样器, 清理通知也使用同一编号."],
      ["prompt_token_ids", "预先分词的完整输入 token ID 列表.", "提供接受历史的起点, 让 Python 核对后续调度片段."],
      ["max_tokens", "可选的输出 token 数量上限.", "离线入口传入与 Rust 相同的上限, 使用 greedy 和 ignore-EOS. 省略时沿用兼容默认值. MTP 与 DSpark 额外为下一轮目标采样预留一个输出 token, 避免生成会被调度器丢弃的草稿."],
    ],
  },
  wireExecute: {
    title: "ExecuteMsg 的 6 个字段", intro: "rpc_id 对应本次往返, step_id 标记调度轮次. 其余字段来自 SchedulerOutput, 序列化时省略 Rust 内部的缓存命中统计.",
    entries: [
      ["rpc_id", "本次 execute 的关联编号.", "execute_result 必须带回同一编号, 让客户端匹配正在等待的调用."],
      ["step_id", "Rust 引擎的轮次编号.", "标识一次计划, 与长期 request_id 和往返 rpc_id 分开."],
      ["scheduled", "本轮单请求片段列表.", "每条带 ID, 起点和两类块表, 交给 planner 核对."],
      ["finished_request_ids", "需要结束清理的请求编号.", "Python 删除对应 histories, sampler 和已提交状态."],
      ["preempted_request_ids", "被回收缓存的请求编号.", "清除旧源, MTP / DSpark 进度与提议记录, 保留确认历史供重新接纳."],
      ["num_batched_tokens", "所有片段的输入总数.", "Python 与实际列表长度求和对照, 再开始模型执行."],
    ],
  },
});

Object.assign(sourceNotes, {
  dsparkConfig: {
    title: "DSparkConfig 的架构与位置字段", intro: "配置对应当前完整实现的固定 checkpoint. 每项尺寸参与张量形状检查和模型计算, 改成其他结构会在加载前拒绝.",
    entries: [
      ["hidden_size", "草稿 hidden 的 5120 维宽度.", "决定 embedding, 归一化和残差向量尺寸."],
      ["intermediate_size", "MLP 的 17408 维中间宽度.", "gate/up 投影扩大向量, down 投影回 hidden_size."],
      ["num_hidden_layers", "五个草稿解码层.", "每层各持注意力, MLP 和 context KV."],
      ["num_attention_heads", "32 个查询头.", "决定 Q 投影的 4096 维输出."],
      ["num_key_value_heads", "8 个 K/V 头.", "每个 K/V 头服务四个 Q 头, 缓存保存较少的头."],
      ["head_dim", "每个头的 128 维宽度.", "用于完整 NeoX RoPE 和 attention 的平方根缩放."],
      ["vocab_size", "248320 个目标词表项.", "共享 head, Markov 投影与 q 的最后维度一致."],
      ["markov_rank", "前一个 ID 的 256 维 latent.", "连接 Markov embedding, 词表偏置与 confidence 拼接."],
      ["block_size", "七个临时 noise 查询行.", "anchor 加六个 MASK, 每行预测后一个候选."],
      ["mask_token_id", "固定 MASK 输入 ID 248070.", "从目标 embedding 查出未来 noise 行的初始向量."],
      ["target_layer_ids", "目标零基层号 5, 19, 33, 47, 61.", "按此顺序拼接同位置的真实 BF16 层输出."],
      ["rms_norm_eps", "RMS 分母中的 1e-6 稳定项.", "用于 context, block, 最后 norm 和 Q/K head norm."],
      ["rope_theta", "RoPE 基数 10000000.", "决定维度相关的基础 inverse frequency."],
      ["rope_factor", "YaRN 插值因子 32.", "将部分频率拉伸到更长上下文."],
      ["original_max_position_embeddings", "原始上下文长度 8192.", "与 beta 参数一起确定插值/外推的混合维度."],
      ["max_position_embeddings", "checkpoint 配置的上限 262144.", "实际目标验证候选还受 worker max_tokens 限制."],
      ["beta_fast", "YaRN 快频段修正参数 32.", "决定插值过渡范围的一端."],
      ["beta_slow", "YaRN 慢频段修正参数 1.", "决定插值过渡范围的另一端."],
    ],
  },
  dsparkFeatures: {
    title: "forward_features 的目标行与层输出", intro: "每行按目标批的 token 顺序对应, 不能按请求输出数量重新排列.",
    entries: [
      ["tokens / batch / caches", "本轮目标 ID, 元数据与目标持久池.", "与普通 forward 相同, 额外收集指定层输出."],
      ["hidden / residual", "当前分支与另存的残差.", "hidden + residual 重建该层输出, 保持 BF16 加法舍入."],
      ["feature_layer_ids / index", "需要读取的层号, 以及当前零基层号.", "按顺序收集 5, 19, 33, 47, 61 层."],
      ["features / torch.cat", "各层同位置向量与最后的特征拼接.", "沿最后维度得到 [T,25600], 保持所有输入行顺序."],
      ["add_rms_norm", "目标最终归一化操作.", "目标 head 使用此 hidden, DSpark 的中间特征另行返回."],
    ],
  },
  dsparkInject: {
    title: "context injection 的位置与页写入", intro: "同一 context 向量由每层自己的 K/V 权重投影, 不经过 block 的 input RMS.",
    entries: [
      ["features / self.fc", "本轮保留的 25600 维目标特征和投影权重.", "线性变换到 5120 维, hidden_norm 得到 context."],
      ["context / shape", "归一化后的特征和 K/V 形状.", "每行投影为 8 个 128 维头."],
      ["positions", "本轮保留输入的绝对位置.", "K 的完整 RoPE 对应同位置 token."],
      ["slots", "由目标 FA 页表求出的物理位置.", "每页 784 个位置, append 只写实际保留行."],
      ["caches / layer", "五个草稿持久池与当前层权重.", "每层写自己的 pool, 相同逻辑页编号指向相应层的数据."],
      ["k / v / prepare_qk", "context K/V 与 K 准备操作.", "context 没有 Q; None 跳过 Q, K 经过 k_norm 和 RoPE."],
      ["inv_freq / attention_factor", "YaRN 频率和 cos/sin 幅度因子.", "使用草稿 checkpoint 的独立位置配置."],
      ["append", "声明修改 cache 的语义操作.", "将 prepared K 与直接投影的 V 写进给定槽."],
    ],
  },
  dsparkContextGraph: {
    title: "context 图的备份, 流依赖和 replay 输入", intro: "1 至 32 行按行数复用同一图, 每轮位置与目的槽可以改变; 缓存所有者先检查逻辑页范围.",
    entries: [
      ["features / positions / slots", "BF16 特征行, int64 绝对位置和目的槽.", "捕获时克隆为静态输入, replay 先校验全部元数据再 copy."],
      ["unit", "已编译的 context injection 函数.", "预热, 捕获与 replay 都用它写本轮 slots; 捕获事务恢复原值, 真正提交由后续 replay 完成."],
      ["caches / pages / offsets", "五层持久池, 本次目的页号与页内位置.", "只备份本次会写的行, 完整前缀和其他后缀位置保留."],
      ["saved / restore", "目的槽的原始 K/V 和恢复函数.", "预热后恢复, 捕获的 finally 再恢复; 异常也执行恢复."],
      ["stream / current", "预热流与调用者当前流.", "预热流先等待当前输入, 当前流随后等待预热写入, 再恢复缓存."],
      ["graph / pool / outputs", "手动 CUDA 图, 独立 context pool 与 None 输出.", "context injection 没有活跃返回张量, replay 执行真正提交."],
      ["MAX_ROWS", "小批量捕获上限 32.", "更多行保持 compiled unit 路径, context 图缓存最多保留 32 项, 覆盖全部合法行数."],
    ],
  },
  decodeGraphKey: {
    title: "目标 graph key 的四个维度", intro: "静态图包含 token 总行数, 请求数, context 范围和每请求 query 上限, 动态地址内容在 replay 时复制.",
    entries: [
      ["token_counts", "本轮每请求实际输入行数.", "由 plan.writes 数量取得, 包括 anchor 和本轮真正验证的候选."],
      ["extent", "按 4096 位置取整的 context 范围.", "限制到 max_model_len, 确定图内静态页表宽度."],
      ["bound / max(token_counts)", "分组 attention 的每请求安全 query 上界.", "DSpark 将真实最大行数向上归入 1, 2, 5, 8 bucket; [1,3] 用 5, [2,2] 用 2. 普通和 MTP 分别固定为 1 和 5."],
      ["next / 1,2,5,8", "覆盖真实最大行数的最小 bucket.", "每个 KV 头对应 6 个 Q 头, 安全上界分别适合 8, 16, 32, 64 行分组 tile, 减少冷编译变体."],
      ["sum(token_counts) / len(token_counts)", "总 token 行数和请求数.", "控制输入与输出张量形状, 和 extent, bound 一起组成四项 key."],
    ],
  },
  benchPrompts: {
    title: "BenchArgs 的合成与自然语料入口", intro: "启动 GPU worker 前解析与校验全部请求 ID, 自然语料可用于独立参数调优.",
    entries: [
      ["batch_size / input_len / output_len / repetitions", "请求数, 每请求输入 / 输出数量与重复次数.", "正数量且 batch 不超过 32, 输入加输出须满足 context 上限."],
      ["prompt_file / parse_prompts", "可选 ID 文件与文本解析函数.", "每行一个请求, 以空格分开目标 tokenizer 编码后的 u32 ID."],
      ["prompts / tokens", "请求向量与每行 ID.", "行数等于 batch_size, 每行长度等于 input_len, 每个 ID 小于 248320."],
      ["max_model_len", "worker 支持的输入加输出上限.", "解析前检查工作量范围, 避免为错误输入先加载模型."],
      ["request / i / 997 / 32000", "未指定文件时的合成 ID 生成变量.", "按请求偏移产生固定有效输入, 保留正式基线负载的确定性."],
    ],
  },
  dsparkHeads: {
    title: "Markov 和 confidence 的条件输入", intro: "第一个 previous 是已提交 anchor, 之后每步换成刚抽取的候选.",
    entries: [
      ["hidden", "当前 noise 位置的最终 5120 维 hidden.", "为 confidence 提供该位置的目标前缀与 block 信息."],
      ["base_logits", "共享目标 head 的当前行词表分数.", "BF16 head 分数加 BF16 Markov bias, 随后交给采样变换."],
      ["previous / latent", "前一个候选 ID 与 256 维 Markov embedding.", "当前 decision 只依赖已经提出的候选."],
      ["markov_w1 / markov_w2", "查询 embedding 与词表投影权重.", "得到当前 ID 对下一候选分布的学习偏置."],
      ["confidence_weight / confidence_bias", "5376 维 confidence 权重与单个偏置.", "由 checkpoint 加载, 对拼接输入执行线性变换, 再用 sigmoid 得到条件接受概率."],
      ["confidence_input", "hidden 与 latent 的 5376 维拼接.", "传给带 bias 的单行线性 confidence 头."],
      ["confidence / sigmoid", "映射到 [0,1] 的预测条件接受概率.", "从首项起累乘并与默认 0.2 阈值比较, 决定是否抽取当前候选."],
    ],
  },
  dsparkProposal: {
    title: "Proposal 的 2 个字段", intro: "候选 ID 的副本和真实 q 保留到下一轮验证或 forget.",
    entries: [
      ["tokens", "本次真实抽取的候选 ID 列表.", "核对调度器传回的验证前缀, 防止 q 对错候选."],
      ["probabilities", "设备上的 [候选数,248320] FP32 q, 或 None.", "随机模式直接供 p/q verifier 使用; greedy 保留 ID 即可."],
    ],
  },
  dsparkStop: {
    title: "逐步提议的前缀和停止变量", intro: "每个位置先检查累计 confidence, 再填语法 mask 与抽样, 首项即可停止, finally 恢复 matcher.",
    entries: [
      ["rid / hidden / base_logits / anchor / limit", "请求编号, block 输出, 首个前一 ID 与候选上限.", "逐步调用同一 Markov/confidence 头, limit 同时满足预算与位置边界."],
      ["sampler / params", "已提交 anchor 的目标 sampler 与用户配置.", "复制当前 history 加临时 prefix, 构造真实 q 而不提交候选."],
      ["candidates / distributions", "已提出的 ID 和对应 q 行.", "下一位置加入候选历史, 下一轮验证按此列表核对切片."],
      ["previous / position", "上一候选的设备 ID 与当前 block 下标.", "confidence 当前行不读取尚未抽取的 ID."],
      ["score / survival", "当前条件置信度和累积前缀概率.", "默认 threshold 0.2, 从首项起在第一个 survival 低于阈值处停止, 实际草稿数可为 0."],
      ["matcher / mask / advanced", "临时语法状态, 当前掩码和成功推进次数.", "每步按 mask 抽样并 accept, finally rollback advanced 次."],
    ],
  },
  dsparkProbability: {
    title: "p/q 接受与残差的张量和检查", intro: "目标每行按真实前缀构造 p, 提议 q 从原始抽样记录取得.",
    entries: [
      ["logits / drafts / draft_probs / bitmask", "目标分数, 原始候选, 对应 q 与目标语法行.", "目标有候选数加一行, q 有候选数行, 词表与设备必须匹配."],
      ["needs_history / target / history_counts", "惩罚条件, 目标 p 和已经提交的计数.", "逐行加入草稿前缀, 最后一行条件为全部候选."],
      ["proposal / candidate / qx / px", "q 矩阵, 候选 ID 及两种分布对候选的概率.", "gather 在每行取当前候选概率, 用于接受比率."],
      ["valid_q", "有限, 非负, 总和接近 1 且候选概率大于 0 的检查.", "只有真实可达的有效提议分布才能验证."],
      ["uniforms / accepted", "均匀随机数与 min(1,px/qx) 比较结果.", "逐行决定是否保留原始候选."],
      ["residual / mass / corrected", "正的 p-q, 残差总量与归一化分布.", "拒绝时从残差抽样, 已接受行允许有限的未使用占位分布."],
      ["distributions / noise / selected", "残差和 bonus 行, 指数随机噪声与所选 ID.", "设备端按这些概率抽样, accepted 行再替换为原始候选."],
      ["valid_p / valid", "目标有限性与最终行有效标志.", "verify_rows 到达无效行时报错, 第一次拒绝结束本轮."],
    ],
  },
});
