// One translation unit keeps all TVM FFI entry functions and device definitions together.
#include "operators/common.cuh"
#include "operators/quantization.cuh"
#include "operators/normalization.cuh"
#include "operators/attention_prepare.cuh"
#include "operators/gdn.cuh"
#include "operators/convolution.cuh"
#include "operators/attention_math.cuh"
#include "operators/decode_attention.cuh"
#include "operators/dspark_decode.cuh"
#include "operators/normalized_quantization.cuh"
